import type { SceneStatus } from '@features/upcomingWave/types/scene.types';

export const ui = {
  lang: 'pt',
  brand: 'Upcoming Wave',
  languagePicker: 'Escolher idioma',
  dominoAria: 'Cadeia de consequências',
  status: {
    today: 'HOJE',
    history: 'HISTÓRIA',
    incident: 'INCIDENTE',
    possible: 'CENÁRIO POSSÍVEL',
    possibleMany: 'CENÁRIOS POSSÍVEIS',
    extreme: 'CENÁRIO EXTREMO',
    answer: 'UM CAMINHO',
  } satisfies Record<SceneStatus, string>,
  quoteMarks: { open: '“', close: '”' },
  why: 'Por quê?',
  copyLink: 'Copiar link desta seção',
  facts: { moreVoices: (count: number) => `+${count} outras vozes`, lessVoices: 'Mostrar menos vozes' },
  upside: { label: 'Se fizermos do jeito certo' },
  readMore: 'Ler mais',
  showLess: 'Mostrar menos',
  chapterEnd: 'Fim do capítulo',
  stepsAria: 'O que acontece, passo a passo',
  factsAria: 'Fatos e fontes',
  explain: {
    eyebrow: 'Por quê?',
    close: 'Fechar explicação',
    prev: 'Passo anterior',
    next: 'Próximo passo',
    done: 'Entendi',
    chainAria: 'Cadeia de causas',
    slide: 'slide',
    step: 'Passo',
    stepOf: (index: number, total: number) => `Passo ${index} de ${total}`,
  },
  voices: {
    eyebrow: 'Vozes · de dentro do setor',
    titleLead: 'Eles concordam em duas coisas.',
    titleAccent: 'Pode ser enorme. E precisa de regras.',
    text: 'Os líderes das empresas que constroem a IA e os cientistas que abriram o caminho. Cada citação leva à sua fonte.',
    signedBy: 'Assinado, entre outros, por',
    source: 'Fonte:',
    swipe: 'Deslize para ver mais →',
  },
  pond: {
    replay: 'Ver de novo ↻',
    day: 'Dia',
    nothing: 'quase nada',
    percentOfPond: (percent: number) => `${percent}% do lago`,
    aria: (day: number, percent: string) => `Dia ${day}: as vitórias-régias cobrem ${percent}% do lago`,
    lessThanOne: 'menos de 1',
  },
  chart: {
    decimal: ',',
    day: '1 dia de trabalho',
    week: '1 semana de trabalho',
    ifContinues: 'se continuar assim ↑',
    uncertain: 'medição incerta',
    showAll: 'Mostrar todas as medições',
    columns: ['Modelo', 'Data', 'Tarefas de até'],
    aria: (title: string, last: string, subtitle: string) => `${title}: de 4 minutos em 2023 para cerca de ${last} em 2026. ${subtitle}`,
  },
  consent: { text: 'Uso o Google Analytics para ver quais seções as pessoas leem. Sem anúncios, sem venda de dados.', accept: 'Aceitar', decline: 'Não, obrigado' },
  scissorsShock: 'onda de demissões',
  scissorsAria: (income: string, spending: string, caption: string) => `${income}: queda; ${spending}: alta. ${caption}`,
};
