import type { Voice } from '@features/upcomingWave/types/voice.types';

// Quotes translated from the original English (verified against the linked source).
// The Suleyman line is our translation of the English edition (ch. 7).
export const voices: Voice[] = [
  {
    id: 'cais',
    featured: true,
    variant: 'statement',
    image: '/images/v2/voice-cais-v1.jpg',
    imageAlt: 'Uma sala de crise: três telas lado a lado - um vírus, um cogumelo atômico e uma rede neural.',
    quotes: ['Mitigar o risco de extinção causado pela IA deve ser uma prioridade global, ao lado de outros riscos em escala social, como pandemias e guerra nuclear.'],
    person: 'Declaração sobre o Risco da IA',
    role: 'Center for AI Safety',
    context: 'maio de 2023',
    source: { label: 'safe.ai', url: 'https://safe.ai/work/statement-on-ai-risk' },
    signatories: ['Sam Altman · OpenAI', 'Demis Hassabis · Google DeepMind', 'Dario Amodei · Anthropic', 'Geoffrey Hinton · ganhador do Nobel', 'Yoshua Bengio · Mila', 'Bill Gates'],
  },
  {
    id: 'hinton',
    featured: true,
    variant: 'figure',
    image: '/images/v2/voice-hinton-v1.jpg',
    imageAlt: 'Uma pessoa pequena diante de uma enorme estrutura luminosa de inteligência.',
    figure: '10 – 20%',
    figureCaption: 'de chance de extinção humana por causa da IA em 30 anos, segundo a estimativa dele.',
    quotes: ['Nunca antes tivemos que lidar com coisas mais inteligentes do que nós.'],
    person: 'Geoffrey Hinton',
    role: 'Ganhador do Nobel, o “padrinho da IA”',
    context: 'BBC Radio 4 · dezembro de 2024',
    source: { label: 'Irish Examiner / Guardian', url: 'https://www.irishexaminer.com/world/arid-41544136.html' },
  },
  {
    id: 'hassabis',
    featured: true,
    variant: 'figure',
    image: '/images/v2/benefit-02-science-v1.jpg',
    imageAlt: 'Uma cientista observa um modelo 3D luminoso de uma proteína.',
    figure: 'Talvez 10 anos',
    figureCaption: 'até que a IA possa ajudar a curar todas as doenças, ele espera - “Não vejo por que não.”',
    quotes: ['Um dia, talvez, possamos curar todas as doenças com a ajuda da IA.'],
    person: 'Demis Hassabis',
    role: 'CEO do Google DeepMind · ganhador do Nobel',
    context: 'CBS 60 Minutes · 2025',
    source: { label: 'CBS News', url: 'https://www.cbsnews.com/news/artificial-intelligence-google-deepmind-ceo-demis-hassabis-60-minutes-transcript/' },
  },
  {
    id: 'gates',
    featured: true,
    variant: 'plain',
    image: '/images/v2/benefit-03-time-v1.jpg',
    imageAlt: 'Uma professora ajoelhada ao lado de uma criança ajuda na lição de casa.',
    quotes: ['O desenvolvimento da IA é tão fundamental quanto a criação do microprocessador, do computador pessoal, da internet e do celular.', 'A IA pode reduzir algumas das piores desigualdades do mundo.'],
    person: 'Bill Gates',
    role: 'Cofundador da Microsoft · Fundação Gates',
    context: 'GatesNotes · março de 2023',
    source: { label: 'GatesNotes', url: 'https://www.gatesnotes.com/The-Age-of-AI-Has-Begun' },
  },
  {
    id: 'altman',
    variant: 'statement',
    image: '/images/v2/voice-altman-v1.jpg',
    imageAlt: 'Uma sala de audiências vazia do Senado dos EUA: a mesa da testemunha, com microfone, de frente para a bancada dos senadores.',
    quotes: [
      'Se esta tecnologia der errado, pode dar muito errado.',
      'Acreditamos que a intervenção regulatória dos governos será fundamental para mitigar os riscos de modelos cada vez mais poderosos.',
    ],
    person: 'Sam Altman',
    role: 'CEO da OpenAI - criadora do ChatGPT',
    context: 'Depoimento no Senado dos EUA · 16 de maio de 2023',
    source: { label: 'Al Jazeera', url: 'https://www.aljazeera.com/news/2023/5/17/chatgpt-boss-tells-us-legislators-regulation-critical-for-ai' },
  },
  {
    id: 'amodei',
    variant: 'figure',
    image: '/images/v2/voice-amodei-v1.jpg',
    imageAlt: 'Um escritório vazio ao amanhecer, com caixas de papelão cheias de objetos de funcionários demitidos sobre as mesas.',
    figure: '50%',
    figureCaption: 'dos empregos de escritório de nível inicial podem desaparecer em 5 anos, com o desemprego disparando para 10–20%, alertou ele em 2025. Em 2026, suavizou essa previsão.',
    quotes: ['Nós, como produtores desta tecnologia, temos o dever e a obrigação de ser honestos sobre o que está por vir.'],
    person: 'Dario Amodei',
    role: 'CEO da Anthropic',
    context: 'Axios · maio de 2025',
    source: { label: 'Axios', url: 'https://www.axios.com/2025/05/28/ai-jobs-white-collar-unemployment-anthropic' },
  },
  {
    id: 'fli',
    variant: 'figure',
    image: '/images/v2/voice-fli-v1.jpg',
    imageAlt: 'Uma parede coberta por milhares de assinaturas; uma mão acrescenta mais uma.',
    figure: '31.000+',
    figureCaption: 'assinaturas em um apelo por uma pausa de pelo menos 6 meses no treinamento dos sistemas mais poderosos. Entre os signatários estão Elon Musk e Steve Wozniak.',
    quotes: ['Devemos arriscar perder o controle da nossa civilização?'],
    person: 'Carta aberta “Pausem os experimentos gigantes de IA”',
    role: 'Future of Life Institute',
    context: 'março de 2023',
    source: { label: 'futureoflife.org', url: 'https://futureoflife.org/open-letter/pause-giant-ai-experiments/' },
  },
  {
    id: 'suleyman',
    variant: 'plain',
    image: '/images/v2/voice-suleyman-v1.jpg',
    imageAlt: 'Um livro aberto em um laboratório; uma hélice de DNA sai das páginas e se transforma em vírus.',
    quotes: ['Um único experimento com patógenos poderia desencadear uma pandemia, um minúsculo evento molecular com ramificações globais.'],
    person: 'Mustafa Suleyman',
    role: 'CEO da Microsoft AI, cofundador da DeepMind, coautor do livro',
    context: '“The Coming Wave”, cap. 7 · 2023',
    source: { label: 'o livro' },
  },
];
