import type { SceneStatus } from '@features/upcomingWave/types/scene.types';

import { paths } from '@routes/paths';

export const ui = {
  lang: 'en',
  brand: 'Upcoming Wave',
  langSwitch: { label: 'PL', href: paths.pl, ariaLabel: 'Wersja polska' } as null | { label: string; href: string; ariaLabel: string },
  dominoAria: 'Chain of consequences',
  status: {
    today: 'TODAY',
    history: 'HISTORY',
    incident: 'INCIDENT',
    possible: 'POSSIBLE SCENARIO',
    possibleMany: 'POSSIBLE SCENARIOS',
    extreme: 'EXTREME SCENARIO',
    answer: 'A WAY FORWARD',
  } satisfies Record<SceneStatus, string>,
  quoteMarks: { open: '“', close: '”' },
  why: 'Why?',
  copyLink: 'Copy link to this section',
  facts: { moreVoices: (count: number) => `+${count} more voices`, lessVoices: 'Show fewer voices' },
  upside: { label: 'If we get it right' },
  readMore: 'Read more',
  showLess: 'Show less',
  chapterEnd: 'End of chapter',
  readingMode: { toShort: 'Short version', toFull: 'Full version', aria: 'Switch between the short and the full version' },
  stepsAria: 'What happens, step by step',
  factsAria: 'Facts and sources',
  explain: {
    eyebrow: 'Why?',
    close: 'Close explanation',
    prev: 'Previous step',
    next: 'Next step',
    done: 'Got it',
    chainAria: 'Chain of causes',
    slide: 'slide',
    step: 'Step',
    stepOf: (index: number, total: number) => `Step ${index} of ${total}`,
  },
  voices: {
    eyebrow: 'Voices · from inside the industry',
    titleLead: 'They agree on two things.',
    titleAccent: 'It could be huge. It needs rules.',
    text: 'The heads of the companies building AI and the scientists who pioneered it. Every quote links to its source.',
    signedBy: 'Signed by, among others',
    source: 'Source:',
  },
  pond: {
    replay: 'Play again ↻',
    day: 'Day',
    nothing: 'almost nothing',
    percentOfPond: (percent: number) => `${percent}% of the pond`,
    aria: (day: number, percent: string) => `Day ${day}: lilies cover ${percent}% of the pond`,
    lessThanOne: 'less than 1',
  },
  chart: {
    decimal: '.',
    day: '1 working day',
    week: '1 working week',
    ifContinues: 'if this continues ↑',
    uncertain: 'uncertain measurement',
    showAll: 'Show all measurements',
    columns: ['Model', 'Date', 'Tasks up to'],
    aria: (title: string, last: string, subtitle: string) => `${title}: from 4 minutes in 2023 to about ${last} in 2026. ${subtitle}`,
  },
  consent: { text: 'I use Google Analytics to see which sections people read. No ads, no selling data.', accept: 'Accept', decline: 'No thanks' },
  scissorsShock: 'wave of layoffs',
};
