import type { Voice } from '@features/upcomingWave/types/voice.types';

// Original English wording of every quote (verified against the linked source).
// The Suleyman line uses the English edition's wording (ch. 7).
export const voices: Voice[] = [
  {
    id: 'cais',
    featured: true,
    variant: 'statement',
    image: '/images/v2/voice-cais-v1.jpg',
    imageAlt: 'A crisis room: three screens side by side — a virus, a mushroom cloud and a neural network.',
    quotes: ['Mitigating the risk of extinction from AI should be a global priority alongside other societal-scale risks such as pandemics and nuclear war.'],
    person: 'Statement on AI Risk',
    role: 'Center for AI Safety',
    context: 'May 2023',
    source: { label: 'safe.ai', url: 'https://safe.ai/work/statement-on-ai-risk' },
    signatories: ['Sam Altman · OpenAI', 'Demis Hassabis · Google DeepMind', 'Dario Amodei · Anthropic', 'Geoffrey Hinton · Nobel laureate', 'Yoshua Bengio · Mila', 'Bill Gates'],
  },
  {
    id: 'hinton',
    featured: true,
    variant: 'figure',
    image: '/images/v2/voice-hinton-v1.jpg',
    imageAlt: 'A small person stands before a huge, glowing structure of intelligence.',
    figure: '10 – 20%',
    figureCaption: 'chance of human extinction from AI within 30 years, by his estimate.',
    quotes: ['We’ve never had to deal with things more intelligent than ourselves before.'],
    person: 'Geoffrey Hinton',
    role: 'Nobel laureate, the “godfather of AI”',
    context: 'BBC Radio 4 · December 2024',
    source: { label: 'Irish Examiner / Guardian', url: 'https://www.irishexaminer.com/world/arid-41544136.html' },
  },
  {
    id: 'amodei',
    variant: 'figure',
    image: '/images/v2/voice-amodei-v1.jpg',
    imageAlt: 'An empty office at dawn, cardboard boxes with laid-off workers’ belongings on the desks.',
    figure: '50%',
    figureCaption: 'of entry-level white-collar jobs could disappear within 5 years, with unemployment spiking to 10–20%, he warned in 2025. In 2026 he softened that forecast.',
    quotes: ['We, as the producers of this technology, have a duty and an obligation to be honest about what is coming.'],
    person: 'Dario Amodei',
    role: 'CEO, Anthropic',
    context: 'Axios · May 2025',
    source: { label: 'Axios', url: 'https://www.axios.com/2025/05/28/ai-jobs-white-collar-unemployment-anthropic' },
  },
  {
    id: 'fli',
    variant: 'figure',
    image: '/images/v2/voice-fli-v1.jpg',
    imageAlt: 'A wall covered in thousands of signatures; a hand adds one more.',
    figure: '31,000+',
    figureCaption: 'signatures on a call for at least a 6-month pause in training the most powerful systems. Signatories include Elon Musk and Steve Wozniak.',
    quotes: ['Should we risk loss of control of our civilization?'],
    person: 'Open letter “Pause Giant AI Experiments”',
    role: 'Future of Life Institute',
    context: 'March 2023',
    source: { label: 'futureoflife.org', url: 'https://futureoflife.org/open-letter/pause-giant-ai-experiments/' },
  },
  {
    id: 'altman',
    featured: true,
    variant: 'wide',
    image: '/images/v2/voice-altman-v1.jpg',
    imageAlt: 'An empty US Senate hearing room: a witness table with a microphone facing the senators’ dais.',
    quotes: [
      'If this technology goes wrong, it can go quite wrong.',
      'We think that regulatory intervention by governments will be critical to mitigate the risks of increasingly powerful models.',
    ],
    person: 'Sam Altman',
    role: 'CEO, OpenAI — maker of ChatGPT',
    context: 'US Senate testimony · May 16, 2023',
    source: { label: 'Al Jazeera', url: 'https://www.aljazeera.com/news/2023/5/17/chatgpt-boss-tells-us-legislators-regulation-critical-for-ai' },
  },
  {
    id: 'suleyman',
    variant: 'plain',
    image: '/images/v2/voice-suleyman-v1.jpg',
    imageAlt: 'An open book in a lab; a DNA helix rises from its pages and turns into a virus.',
    quotes: ['A single pathogenic experiment could spark a pandemic, a tiny molecular event with global ramifications.'],
    person: 'Mustafa Suleyman',
    role: 'DeepMind co-founder, author of the book',
    context: '“The Coming Wave”, ch. 7 · 2023',
    source: { label: 'the book' },
  },
];
