import type { SceneStatus } from '@features/upcomingWave/types/scene.types';

export const ui = {
  lang: 'de',
  brand: 'Upcoming Wave',
  languagePicker: 'Sprache wählen',
  dominoAria: 'Kette der Folgen',
  status: {
    today: 'HEUTE',
    history: 'GESCHICHTE',
    incident: 'VORFALL',
    possible: 'MÖGLICHES SZENARIO',
    possibleMany: 'MÖGLICHE SZENARIEN',
    extreme: 'EXTREMSZENARIO',
    answer: 'EIN WEG NACH VORN',
  } satisfies Record<SceneStatus, string>,
  quoteMarks: { open: '„', close: '“' },
  why: 'Warum?',
  copyLink: 'Link zu diesem Abschnitt kopieren',
  facts: { moreVoices: (count: number) => `+${count} weitere Stimmen`, lessVoices: 'Weniger Stimmen zeigen' },
  upside: { label: 'Wenn wir es richtig machen' },
  readMore: 'Weiterlesen',
  showLess: 'Weniger zeigen',
  chapterEnd: 'Ende des Kapitels',
  readingMode: { toShort: 'Kurzfassung', toFull: 'Langfassung', aria: 'Zwischen Kurz- und Langfassung wechseln' },
  stepsAria: 'Was passiert, Schritt für Schritt',
  factsAria: 'Fakten und Quellen',
  explain: {
    eyebrow: 'Warum?',
    close: 'Erklärung schließen',
    prev: 'Vorheriger Schritt',
    next: 'Nächster Schritt',
    done: 'Verstanden',
    chainAria: 'Kette der Ursachen',
    slide: 'Folie',
    step: 'Schritt',
    stepOf: (index: number, total: number) => `Schritt ${index} von ${total}`,
  },
  voices: {
    eyebrow: 'Stimmen · aus der Branche',
    titleLead: 'In zwei Punkten sind sie sich einig.',
    titleAccent: 'Es könnte riesig werden. Es braucht Regeln.',
    text: 'Die Chefs der Firmen, die KI bauen, und die Forschenden, die sie mit erfunden haben. Jedes Zitat ist mit seiner Quelle verlinkt.',
    signedBy: 'Unterzeichnet u. a. von',
    source: 'Quelle:',
    swipe: 'Wischen für mehr →',
  },
  pond: {
    replay: 'Nochmal ↻',
    day: 'Tag',
    nothing: 'fast nichts',
    percentOfPond: (percent: number) => `${percent}\u00a0% des Teichs`,
    aria: (day: number, percent: string) => `Tag ${day}: Seerosen bedecken ${percent}\u00a0% des Teichs`,
    lessThanOne: 'weniger als 1',
  },
  chart: {
    decimal: ',',
    day: '1 Arbeitstag',
    week: '1 Arbeitswoche',
    ifContinues: 'wenn es so weitergeht ↑',
    uncertain: 'unsichere Messung',
    showAll: 'Alle Messungen zeigen',
    columns: ['Modell', 'Datum', 'Aufgaben bis'],
    aria: (title: string, last: string, subtitle: string) => `${title}: von 4 Minuten im Jahr 2023 auf etwa ${last} im Jahr 2026. ${subtitle}`,
  },
  consent: { text: 'Ich nutze Google Analytics, um zu sehen, welche Abschnitte gelesen werden. Keine Werbung, kein Verkauf von Daten.', accept: 'Akzeptieren', decline: 'Nein danke' },
  scissorsShock: 'Entlassungswelle',
  scissorsAria: (income: string, spending: string, caption: string) => `${income} sinken, ${spending} steigen. ${caption}`,
};
