import type { Voice } from '@features/upcomingWave/types/voice.types';

// German translation of every quote (originals verified against the linked source).
// The Suleyman line is our translation of the English edition (ch. 7).
export const voices: Voice[] = [
  {
    id: 'cais',
    featured: true,
    variant: 'statement',
    image: '/images/v2/voice-cais-v1.jpg',
    imageAlt: 'Ein Krisenraum: drei Bildschirme nebeneinander - ein Virus, ein Atompilz und ein neuronales Netz.',
    quotes: ['Das Risiko der Auslöschung durch KI zu verringern, sollte eine globale Priorität sein - neben anderen Risiken für die gesamte Gesellschaft wie Pandemien und Atomkrieg.'],
    person: 'Erklärung zum KI-Risiko',
    role: 'Center for AI Safety',
    context: 'Mai 2023',
    source: { label: 'safe.ai', url: 'https://safe.ai/work/statement-on-ai-risk' },
    signatories: ['Sam Altman · OpenAI', 'Demis Hassabis · Google DeepMind', 'Dario Amodei · Anthropic', 'Geoffrey Hinton · Nobelpreisträger', 'Yoshua Bengio · Mila', 'Bill Gates'],
  },
  {
    id: 'hinton',
    featured: true,
    variant: 'figure',
    image: '/images/v2/voice-hinton-v1.jpg',
    imageAlt: 'Ein kleiner Mensch steht vor einer riesigen, leuchtenden Struktur aus Intelligenz.',
    figure: '10-20 %',
    figureCaption: 'Wahrscheinlichkeit, dass die Menschheit innerhalb von 30 Jahren durch KI ausgelöscht wird - nach seiner Schätzung.',
    quotes: ['Wir hatten es noch nie mit Dingen zu tun, die intelligenter sind als wir selbst.'],
    person: 'Geoffrey Hinton',
    role: 'Nobelpreisträger, der „Pate der KI“',
    context: 'BBC Radio 4 · Dezember 2024',
    source: { label: 'Irish Examiner / Guardian', url: 'https://www.irishexaminer.com/world/arid-41544136.html' },
  },
  {
    id: 'hassabis',
    featured: true,
    variant: 'figure',
    image: '/images/v2/benefit-02-science-v1.jpg',
    imageAlt: 'Eine Wissenschaftlerin betrachtet ein leuchtendes 3D-Modell eines Proteins.',
    figure: '~10 Jahre',
    figureCaption: 'bis die Heilung aller Krankheiten in Reichweite sein könnte, sagt er - „Ich sehe nicht, warum nicht.“',
    quotes: ['Vielleicht können wir eines Tages mit Hilfe von KI alle Krankheiten heilen.'],
    person: 'Demis Hassabis',
    role: 'CEO, Google DeepMind · Nobelpreisträger',
    context: 'CBS 60 Minutes · 2025',
    source: { label: 'CBS News', url: 'https://www.cbsnews.com/news/artificial-intelligence-google-deepmind-ceo-demis-hassabis-60-minutes-transcript/' },
  },
  {
    id: 'gates',
    featured: true,
    variant: 'plain',
    image: '/images/v2/benefit-03-time-v1.jpg',
    imageAlt: 'Eine Lehrerin kniet neben einem Kind und hilft ihm bei den Schulaufgaben.',
    quotes: ['Die Entwicklung der KI ist so grundlegend wie die Erfindung des Mikroprozessors, des PCs, des Internets und des Mobiltelefons.', 'KI kann einige der schlimmsten Ungerechtigkeiten der Welt verringern.'],
    person: 'Bill Gates',
    role: 'Mitgründer, Microsoft · Gates Foundation',
    context: 'GatesNotes · März 2023',
    source: { label: 'GatesNotes', url: 'https://www.gatesnotes.com/The-Age-of-AI-Has-Begun' },
  },
  {
    id: 'altman',
    featured: true,
    variant: 'statement',
    image: '/images/v2/voice-altman-v1.jpg',
    imageAlt: 'Ein leerer Anhörungssaal im US-Senat: ein Zeugentisch mit Mikrofon vor dem Podium der Senatoren.',
    quotes: [
      'Wenn diese Technologie schiefgeht, kann sie ziemlich schiefgehen.',
      'Wir glauben, dass regulierende Eingriffe von Regierungen entscheidend sein werden, um die Risiken immer leistungsfähigerer Modelle zu verringern.',
    ],
    person: 'Sam Altman',
    role: 'CEO, OpenAI - Hersteller von ChatGPT',
    context: 'Aussage vor dem US-Senat · 16. Mai 2023',
    source: { label: 'Al Jazeera', url: 'https://www.aljazeera.com/news/2023/5/17/chatgpt-boss-tells-us-legislators-regulation-critical-for-ai' },
  },
  {
    id: 'amodei',
    variant: 'figure',
    image: '/images/v2/voice-amodei-v1.jpg',
    imageAlt: 'Ein leeres Büro im Morgengrauen, auf den Schreibtischen Kartons mit den Sachen entlassener Mitarbeiter.',
    figure: '50 %',
    figureCaption: 'der Einstiegsjobs im Büro könnten innerhalb von 5 Jahren verschwinden, die Arbeitslosigkeit auf 10-20 % steigen, warnte er 2025. 2026 schwächte er diese Prognose ab.',
    quotes: ['Wir als Hersteller dieser Technologie haben die Pflicht und die Verantwortung, ehrlich zu sagen, was auf uns zukommt.'],
    person: 'Dario Amodei',
    role: 'CEO, Anthropic',
    context: 'Axios · Mai 2025',
    source: { label: 'Axios', url: 'https://www.axios.com/2025/05/28/ai-jobs-white-collar-unemployment-anthropic' },
  },
  {
    id: 'fli',
    variant: 'figure',
    image: '/images/v2/voice-fli-v1.jpg',
    imageAlt: 'Eine Wand voller Tausender Unterschriften; eine Hand fügt eine weitere hinzu.',
    figure: '31.000+',
    figureCaption: 'Unterschriften unter einem Aufruf, das Training der leistungsfähigsten Systeme mindestens 6 Monate zu pausieren. Unterzeichnet haben u. a. Elon Musk und Steve Wozniak.',
    quotes: ['Sollten wir riskieren, die Kontrolle über unsere Zivilisation zu verlieren?'],
    person: 'Offener Brief „Pause Giant AI Experiments“',
    role: 'Future of Life Institute',
    context: 'März 2023',
    source: { label: 'futureoflife.org', url: 'https://futureoflife.org/open-letter/pause-giant-ai-experiments/' },
  },
  {
    id: 'suleyman',
    variant: 'plain',
    image: '/images/v2/voice-suleyman-v1.jpg',
    imageAlt: 'Ein aufgeschlagenes Buch in einem Labor; aus seinen Seiten steigt eine DNA-Helix auf und wird zu einem Virus.',
    quotes: ['Ein einziges Experiment mit Krankheitserregern könnte eine Pandemie auslösen - ein winziges molekulares Ereignis mit globalen Folgen.'],
    person: 'Mustafa Suleyman',
    role: 'Mitgründer von DeepMind, Autor des Buches',
    context: '„The Coming Wave“, Kap. 7 · 2023',
    source: { label: 'das Buch' },
  },
];
