import type { SceneStatus } from '@features/upcomingWave/types/scene.types';

export const ui = {
  lang: 'es',
  brand: 'Upcoming Wave',
  languagePicker: 'Elegir idioma',
  dominoAria: 'Cadena de consecuencias',
  status: {
    today: 'HOY',
    history: 'HISTORIA',
    incident: 'INCIDENTE',
    possible: 'ESCENARIO POSIBLE',
    possibleMany: 'ESCENARIOS POSIBLES',
    extreme: 'ESCENARIO EXTREMO',
    answer: 'UN CAMINO',
  } satisfies Record<SceneStatus, string>,
  quoteMarks: { open: '«', close: '»' },
  why: '¿Por qué?',
  copyLink: 'Copiar enlace a esta sección',
  facts: { moreVoices: (count: number) => `+${count} voces más`, lessVoices: 'Mostrar menos voces' },
  upside: { label: 'Si lo hacemos bien' },
  readMore: 'Leer más',
  showLess: 'Mostrar menos',
  chapterEnd: 'Fin del capítulo',
  readingMode: { toShort: 'Versión corta', toFull: 'Versión completa', aria: 'Cambiar entre la versión corta y la completa' },
  stepsAria: 'Qué ocurre, paso a paso',
  factsAria: 'Datos y fuentes',
  explain: {
    eyebrow: '¿Por qué?',
    close: 'Cerrar explicación',
    prev: 'Paso anterior',
    next: 'Paso siguiente',
    done: 'Entendido',
    chainAria: 'Cadena de causas',
    slide: 'diapositiva',
    step: 'Paso',
    stepOf: (index: number, total: number) => `Paso ${index} de ${total}`,
  },
  voices: {
    eyebrow: 'Voces · desde dentro del sector',
    titleLead: 'Coinciden en dos cosas.',
    titleAccent: 'Puede ser enorme. Necesita reglas.',
    text: 'Los directivos de las empresas que construyen la IA y los científicos que la hicieron posible. Cada cita enlaza a su fuente.',
    signedBy: 'Firmado, entre otros, por',
    source: 'Fuente:',
    swipe: 'Desliza para ver más →',
  },
  pond: {
    replay: 'Ver otra vez ↻',
    day: 'Día',
    nothing: 'casi nada',
    percentOfPond: (percent: number) => `${percent}% del estanque`,
    aria: (day: number, percent: string) => `Día ${day}: los nenúfares cubren ${percent}% del estanque`,
    lessThanOne: 'menos del 1',
  },
  chart: {
    decimal: ',',
    day: '1 jornada laboral',
    week: '1 semana laboral',
    ifContinues: 'si esto sigue así ↑',
    uncertain: 'medición incierta',
    showAll: 'Ver todas las mediciones',
    columns: ['Modelo', 'Fecha', 'Tareas de hasta'],
    aria: (title: string, last: string, subtitle: string) => `${title}: de 4 minutos en 2023 a unas ${last} en 2026. ${subtitle}`,
  },
  consent: { text: 'Uso Google Analytics para saber qué secciones lee la gente. Sin anuncios y sin vender datos.', accept: 'Aceptar', decline: 'No, gracias' },
  scissorsShock: 'ola de despidos',
  scissorsAria: (income: string, spending: string, caption: string) => `Los ${income} caen y el ${spending} sube. ${caption}`,
};
