import type { Voice } from '@features/upcomingWave/types/voice.types';

// Quotes are translated into Spanish from their original English wording (verified against the linked source).
// The Suleyman line is our translation of the English edition (ch. 7).
export const voices: Voice[] = [
  {
    id: 'cais',
    featured: true,
    variant: 'statement',
    image: '/images/v2/voice-cais-v1.jpg',
    imageAlt: 'Una sala de crisis: tres pantallas una al lado de otra, con un virus, un hongo nuclear y una red neuronal.',
    quotes: ['Mitigar el riesgo de extinción por la IA debería ser una prioridad mundial, junto con otros riesgos a escala social como las pandemias y la guerra nuclear.'],
    person: 'Declaración sobre el riesgo de la IA',
    role: 'Center for AI Safety',
    context: 'Mayo de 2023',
    source: { label: 'safe.ai', url: 'https://safe.ai/work/statement-on-ai-risk' },
    signatories: ['Sam Altman · OpenAI', 'Demis Hassabis · Google DeepMind', 'Dario Amodei · Anthropic', 'Geoffrey Hinton · premio Nobel', 'Yoshua Bengio · Mila', 'Bill Gates'],
  },
  {
    id: 'hinton',
    featured: true,
    variant: 'figure',
    image: '/images/v2/voice-hinton-v1.jpg',
    imageAlt: 'Una persona pequeña ante una estructura de inteligencia enorme y luminosa.',
    figure: '10-20%',
    figureCaption: 'de probabilidad de que la IA extinga a la humanidad en 30 años, según su estimación.',
    quotes: ['Nunca hemos tenido que lidiar con cosas más inteligentes que nosotros.'],
    person: 'Geoffrey Hinton',
    role: 'Premio Nobel, el «padrino de la IA»',
    context: 'BBC Radio 4 · diciembre de 2024',
    source: { label: 'Irish Examiner / Guardian', url: 'https://www.irishexaminer.com/world/arid-41544136.html' },
  },
  {
    id: 'hassabis',
    featured: true,
    variant: 'figure',
    image: '/images/v2/benefit-02-science-v1.jpg',
    imageAlt: 'Una científica observa un modelo 3D luminoso de una proteína.',
    figure: 'Quizá 10 años',
    figureCaption: 'para que la IA pueda ayudar a curar todas las enfermedades, según espera: «No veo por qué no».',
    quotes: ['Quizá algún día podamos curar todas las enfermedades con ayuda de la IA.'],
    person: 'Demis Hassabis',
    role: 'CEO de Google DeepMind · premio Nobel',
    context: 'CBS 60 Minutes · 2025',
    source: { label: 'CBS News', url: 'https://www.cbsnews.com/news/artificial-intelligence-google-deepmind-ceo-demis-hassabis-60-minutes-transcript/' },
  },
  {
    id: 'gates',
    featured: true,
    variant: 'plain',
    image: '/images/v2/benefit-03-time-v1.jpg',
    imageAlt: 'Una maestra se arrodilla junto a un niño y le ayuda con las tareas escolares.',
    quotes: ['El desarrollo de la IA es tan fundamental como la creación del microprocesador, la computadora personal, internet y el teléfono móvil.', 'La IA puede reducir algunas de las peores desigualdades del mundo.'],
    person: 'Bill Gates',
    role: 'Cofundador de Microsoft · Gates Foundation',
    context: 'GatesNotes · marzo de 2023',
    source: { label: 'GatesNotes', url: 'https://www.gatesnotes.com/The-Age-of-AI-Has-Begun' },
  },
  {
    id: 'altman',
    featured: true,
    variant: 'statement',
    image: '/images/v2/voice-altman-v1.jpg',
    imageAlt: 'Una sala de audiencias vacía del Senado de EE. UU.: la mesa del testigo con un micrófono frente al estrado de los senadores.',
    quotes: [
      'Si esta tecnología sale mal, puede salir bastante mal.',
      'Creemos que la intervención regulatoria de los gobiernos será crucial para mitigar los riesgos de modelos cada vez más potentes.',
    ],
    person: 'Sam Altman',
    role: 'CEO de OpenAI, creadora de ChatGPT',
    context: 'Declaración ante el Senado de EE. UU. · 16 de mayo de 2023',
    source: { label: 'Al Jazeera', url: 'https://www.aljazeera.com/news/2023/5/17/chatgpt-boss-tells-us-legislators-regulation-critical-for-ai' },
  },
  {
    id: 'amodei',
    variant: 'figure',
    image: '/images/v2/voice-amodei-v1.jpg',
    imageAlt: 'Una oficina vacía al amanecer, con cajas de cartón llenas de las cosas de los empleados despedidos sobre las mesas.',
    figure: '50%',
    figureCaption: 'de los empleos de oficina de nivel inicial podrían desaparecer en 5 años, con un desempleo disparado al 10-20%, advirtió en 2025. En 2026 suavizó ese pronóstico.',
    quotes: ['Nosotros, como productores de esta tecnología, tenemos el deber y la obligación de ser honestos sobre lo que se avecina.'],
    person: 'Dario Amodei',
    role: 'CEO de Anthropic',
    context: 'Axios · mayo de 2025',
    source: { label: 'Axios', url: 'https://www.axios.com/2025/05/28/ai-jobs-white-collar-unemployment-anthropic' },
  },
  {
    id: 'fli',
    variant: 'figure',
    image: '/images/v2/voice-fli-v1.jpg',
    imageAlt: 'Una pared cubierta de miles de firmas; una mano añade una más.',
    figure: '31 000+',
    figureCaption: 'firmas en un llamamiento a pausar al menos 6 meses el entrenamiento de los sistemas más potentes. Entre los firmantes, Elon Musk y Steve Wozniak.',
    quotes: ['¿Deberíamos arriesgarnos a perder el control de nuestra civilización?'],
    person: 'Carta abierta «Pause Giant AI Experiments»',
    role: 'Future of Life Institute',
    context: 'Marzo de 2023',
    source: { label: 'futureoflife.org', url: 'https://futureoflife.org/open-letter/pause-giant-ai-experiments/' },
  },
  {
    id: 'suleyman',
    variant: 'plain',
    image: '/images/v2/voice-suleyman-v1.jpg',
    imageAlt: 'Un libro abierto en un laboratorio; de sus páginas surge una hélice de ADN que se convierte en un virus.',
    quotes: ['Un solo experimento con patógenos podría desencadenar una pandemia, un diminuto suceso molecular con consecuencias globales.'],
    person: 'Mustafa Suleyman',
    role: 'CEO de Microsoft AI, cofundador de DeepMind, coautor del libro',
    context: '«The Coming Wave», cap. 7 · 2023',
    source: { label: 'el libro' },
  },
];
