import type { SceneStatus } from '@features/upcomingWave/types/scene.types';

export const ui = {
  lang: 'ja',
  brand: 'Upcoming Wave',
  languagePicker: '言語を選択',
  dominoAria: '結果の連鎖',
  status: {
    today: '現在',
    history: '歴史',
    incident: 'インシデント',
    possible: '起こりうるシナリオ',
    possibleMany: '起こりうるシナリオ',
    extreme: '極端なシナリオ',
    answer: '進むべき道',
  } satisfies Record<SceneStatus, string>,
  quoteMarks: { open: '「', close: '」' },
  why: 'なぜ？',
  copyLink: 'このセクションへのリンクをコピー',
  facts: { moreVoices: (count: number) => `ほか${count}人の声を見る`, lessVoices: '声の表示を減らす' },
  upside: { label: 'うまくいけば' },
  readMore: '続きを読む',
  showLess: '閉じる',
  chapterEnd: '章の終わり',
  readingMode: { toShort: '短縮版', toFull: '完全版', aria: '短縮版と完全版を切り替える' },
  stepsAria: '何が起こるか、段階ごとに',
  factsAria: '事実と出典',
  explain: {
    eyebrow: 'なぜ？',
    close: '説明を閉じる',
    prev: '前のステップ',
    next: '次のステップ',
    done: 'わかりました',
    chainAria: '原因の連鎖',
    slide: 'スライド',
    step: 'ステップ',
    stepOf: (index: number, total: number) => `ステップ ${index}/${total}`,
  },
  voices: {
    eyebrow: '業界の内側からの声',
    titleLead: '一致しているのは二つの点。',
    titleAccent: '影響は巨大になりうる。ルールが必要だ。',
    text: 'AIを開発する企業のトップと、その道を切り開いた科学者たち。すべての引用に、出典へのリンクを付けています。',
    signedBy: '主な署名者',
    source: '出典：',
    swipe: 'スワイプして続きを見る →',
  },
  pond: {
    replay: 'もう一度再生 ↻',
    day: '経過日数',
    nothing: 'ほとんどゼロ',
    percentOfPond: (percent: number) => `池の${percent}%`,
    aria: (day: number, percent: string) => `${day}日目：スイレンが池の${percent}%を覆っています`,
    lessThanOne: '1未満',
  },
  chart: {
    decimal: '.',
    day: '1日の勤務時間',
    week: '1週間の勤務時間',
    ifContinues: 'このまま続けば ↑',
    uncertain: '不確かな測定値',
    showAll: 'すべての測定値を表示',
    columns: ['モデル', '時期', 'タスクの長さ'],
    aria: (title: string, last: string, subtitle: string) => `${title}：2023年の4分から、2026年には約${last}に。${subtitle}`,
  },
  consent: { text: 'どのセクションが読まれているかを知るため、Google アナリティクスを使っています。広告はなく、データを売ることもありません。', accept: '同意する', decline: '同意しない' },
  scissorsShock: '解雇の波',
  scissorsAria: (income: string, spending: string, caption: string) => `${income}は減り、${spending}は増える。${caption}`,
};
