import type { Voice } from '@features/upcomingWave/types/voice.types';

// Our Japanese translation of the original English wording (verified against the linked source).
// The Suleyman line is translated from the English edition (ch. 7).
export const voices: Voice[] = [
  {
    id: 'cais',
    featured: true,
    variant: 'statement',
    image: '/images/v2/voice-cais-v1.jpg',
    imageAlt: '危機対策室。3つの画面が並び、ウイルス、キノコ雲、ニューラルネットワークが映っている。',
    quotes: ['AIによる人類絶滅のリスクを軽減することは、パンデミックや核戦争といった社会規模の他のリスクと並んで、世界的な優先課題とされるべきだ。'],
    person: 'AIのリスクに関する声明',
    role: 'Center for AI Safety',
    context: '2023年5月',
    source: { label: 'safe.ai', url: 'https://safe.ai/work/statement-on-ai-risk' },
    signatories: ['サム・アルトマン · OpenAI', 'デミス・ハサビス · Google DeepMind', 'ダリオ・アモデイ · Anthropic', 'ジェフリー・ヒントン · ノーベル賞受賞者', 'ヨシュア・ベンジオ · Mila', 'ビル・ゲイツ'],
  },
  {
    id: 'hinton',
    featured: true,
    variant: 'figure',
    image: '/images/v2/voice-hinton-v1.jpg',
    imageAlt: '光り輝く巨大な知性の構造物の前に、小さな人がひとり立っている。',
    figure: '10〜20%',
    figureCaption: '30年以内にAIによって人類が絶滅する確率。彼自身の推計です。',
    quotes: ['私たちはこれまで、自分たちより賢いものを相手にしたことが一度もない。'],
    person: 'ジェフリー・ヒントン',
    role: 'ノーベル賞受賞者、「AIのゴッドファーザー」',
    context: 'BBC Radio 4 · 2024年12月',
    source: { label: 'Irish Examiner / Guardian', url: 'https://www.irishexaminer.com/world/arid-41544136.html' },
  },
  {
    id: 'hassabis',
    featured: true,
    variant: 'figure',
    image: '/images/v2/benefit-02-science-v1.jpg',
    imageAlt: '科学者が、光るタンパク質の3Dモデルを見つめている。',
    figure: '約10年',
    figureCaption: 'あらゆる病気の治癒が手の届くところに来るまでの期間だと彼は言います。「そうならない理由が見当たらない」。',
    quotes: ['いつの日か、AIの助けを借りて、あらゆる病気を治せるかもしれない。'],
    person: 'デミス・ハサビス',
    role: 'Google DeepMind CEO · ノーベル賞受賞者',
    context: 'CBS 60 Minutes · 2025年',
    source: { label: 'CBS News', url: 'https://www.cbsnews.com/news/artificial-intelligence-google-deepmind-ceo-demis-hassabis-60-minutes-transcript/' },
  },
  {
    id: 'gates',
    featured: true,
    variant: 'plain',
    image: '/images/v2/benefit-03-time-v1.jpg',
    imageAlt: '教師が子どものそばにひざまずき、勉強を手伝っている。',
    quotes: ['AIの開発は、マイクロプロセッサ、パソコン、インターネット、携帯電話の誕生と同じくらい根本的なものだ。', 'AIは、世界で最も深刻な不平等のいくつかを減らすことができる。'],
    person: 'ビル・ゲイツ',
    role: 'Microsoft共同創業者 · ゲイツ財団',
    context: 'GatesNotes · 2023年3月',
    source: { label: 'GatesNotes', url: 'https://www.gatesnotes.com/The-Age-of-AI-Has-Begun' },
  },
  {
    id: 'altman',
    featured: true,
    variant: 'statement',
    image: '/images/v2/voice-altman-v1.jpg',
    imageAlt: '誰もいない米上院の公聴会室。マイクの置かれた証人席が、上院議員の壇席と向き合っている。',
    quotes: [
      'この技術がうまくいかなければ、事態はかなり悪くなりうる。',
      'ますます強力になるモデルのリスクを軽減するには、政府による規制介入が不可欠だと考えている。',
    ],
    person: 'サム・アルトマン',
    role: 'OpenAI CEO（ChatGPTの開発元）',
    context: '米上院での証言 · 2023年5月16日',
    source: { label: 'Al Jazeera', url: 'https://www.aljazeera.com/news/2023/5/17/chatgpt-boss-tells-us-legislators-regulation-critical-for-ai' },
  },
  {
    id: 'amodei',
    variant: 'figure',
    image: '/images/v2/voice-amodei-v1.jpg',
    imageAlt: '夜明けの誰もいないオフィス。机の上には、解雇された社員の私物が入った段ボール箱。',
    figure: '50%',
    figureCaption: '5年以内に消えうる、ホワイトカラーの初級職の割合。失業率は10〜20%に跳ね上がりうると、彼は2025年に警告しました。2026年には、この予測を和らげています。',
    quotes: ['この技術を生み出す者として、私たちには、何が起ころうとしているのかについて正直である責務と義務がある。'],
    person: 'ダリオ・アモデイ',
    role: 'Anthropic CEO',
    context: 'Axios · 2025年5月',
    source: { label: 'Axios', url: 'https://www.axios.com/2025/05/28/ai-jobs-white-collar-unemployment-anthropic' },
  },
  {
    id: 'fli',
    variant: 'figure',
    image: '/images/v2/voice-fli-v1.jpg',
    imageAlt: '何千もの署名で埋め尽くされた壁に、手がもう一つ署名を書き加えている。',
    figure: '3万1,000以上',
    figureCaption: '最も強力なシステムの訓練を少なくとも6か月停止するよう求める呼びかけへの署名数。署名者にはイーロン・マスクやスティーブ・ウォズニアックも含まれます。',
    quotes: ['私たちは、文明の制御を失う危険を冒すべきなのか？'],
    person: '公開書簡「巨大AI実験の一時停止を」',
    role: 'Future of Life Institute',
    context: '2023年3月',
    source: { label: 'futureoflife.org', url: 'https://futureoflife.org/open-letter/pause-giant-ai-experiments/' },
  },
  {
    id: 'suleyman',
    variant: 'plain',
    image: '/images/v2/voice-suleyman-v1.jpg',
    imageAlt: '研究室に開かれた一冊の本。ページからDNAのらせんが立ち上り、ウイルスに変わっていく。',
    quotes: ['たった一つの病原体実験がパンデミックを引き起こしうる。ごく小さな分子レベルの出来事が、世界規模の影響をもたらすのだ。'],
    person: 'ムスタファ・スレイマン',
    role: 'DeepMind共同創業者、本書の著者',
    context: '『The Coming Wave』第7章 · 2023年',
    source: { label: '本書' },
  },
];
