import type { Scene } from '@features/upcomingWave/types/scene.types';

import { acceleration } from '@features/upcomingWave/content/pl/acceleration';
import { calm } from '@features/upcomingWave/content/pl/calm';
import { split } from '@features/upcomingWave/content/pl/closing';

const images = {
  layoffs: '/images/v2/threat-02-layoffs-v1.jpg',
  aiRules: '/images/v2/threat-02-ai-rules-v1.jpg',
  bio: '/images/v2/threat-03-bio-v1.jpg',
  remote: '/images/v2/work-01-remote-v1.jpg',
  aiFaster: '/images/v2/work-02-ai-faster-v2.jpg',
  owners: '/images/v2/work-03-owners-v1.jpg',
  callcenter: '/images/v2/jobs-01-callcenter-v1.jpg',
  legal: '/images/v2/jobs-02-legal-v1.jpg',
  design: '/images/v2/jobs-03-design-v1.jpg',
  translator: '/images/v2/jobs-04-translator-v1.jpg',
  warehouse: '/images/v2/jobs-05-warehouse-v1.jpg',
  driver: '/images/v2/jobs-06-driver-v1.jpg',
  queue: '/images/v2/trades-01-queue-v1.jpg',
  tooMany: '/images/v2/trades-02-too-many-v1.jpg',
  robot: '/images/v2/trades-03-robot-v1.jpg',
  bills: '/images/v2/demand-01-bills-v1.jpg',
  emptyStore: '/images/v2/demand-02-empty-store-v1.jpg',
  closing: '/images/v2/demand-03-closing-v1.jpg',
  workFunds: '/images/v2/state-01-work-funds-v1.jpg',
  cuts: '/images/v2/state-02-cuts-v1.jpg',
  strain: '/images/v2/state-03-strain-v1.jpg',
  depression: '/images/v2/history-01-depression-v1.jpg',
  factory: '/images/v2/history-02-factory-v1.jpg',
  anger: '/images/v2/history-03-anger-v1.jpg',
  cage: '/images/v2/breach-01-cage-v1.jpg',
  swarm: '/images/v2/breach-02-swarm-v1.jpg',
  search: '/images/v2/breach-03-search-v1.jpg',
  sim: '/images/v2/useless-01-sim-v1.jpg',
  everywhere: '/images/v2/useless-02-everywhere-v1.jpg',
  idle: '/images/v2/useless-03-idle-v1.jpg',
  speed: '/images/v2/rules-01-speed-v1.jpg',
  noRules: '/images/v2/threat-03-no-rules-v1.jpg',
  citizens: '/images/v2/rules-03-citizens-v2.jpg',
  medicine: '/images/v2/benefit-01-medicine-v1.jpg',
  science: '/images/v2/benefit-02-science-v1.jpg',
  time: '/images/v2/benefit-03-time-v1.jpg',
  energy: '/images/v2/benefit-04-energy-v1.jpg',
  food: '/images/v2/benefit-05-food-v1.jpg',
  forecast: '/images/v2/benefit-06-forecast-v1.jpg',
};

const sources = {
  ilo: { label: 'ILO–NASK, 2025', url: 'https://www.ilo.org/resource/news/one-four-jobs-risk-being-transformed-genai-new-ilo%E2%80%93nask-global-index-shows' },
  imf: { label: 'MFW, 2024', url: 'https://www.cnbc.com/2024/01/15/imf-warns-ai-to-hit-almost-40percent-of-global-employment-worsen-inequality.html' },
  stanford: { label: 'Stanford, 2026', url: 'https://digitaleconomy.stanford.edu/news/canariesaug26/' },
  salesforce: { label: 'CNBC', url: 'https://www.cnbc.com/2025/09/02/salesforce-ceo-confirms-4000-layoffs-because-i-need-less-heads-with-ai.html' },
  klarna: { label: 'CNBC', url: 'https://www.cnbc.com/2025/05/14/klarna-ceo-says-ai-helped-company-shrink-workforce-by-40percent.html' },
  amazon: { label: 'Amazon', url: 'https://www.aboutamazon.com/news/company-news/amazon-ceo-andy-jassy-on-generative-ai' },
  hintonDoac: { label: 'Diary of a CEO, 2025', url: 'https://singjupost.com/transcript-of-godfather-of-ai-i-tried-to-warn-them-but-weve-already-lost-control/' },
  hintonFt: { label: 'Financial Times / Fortune, 2025', url: 'https://fortune.com/2025/09/06/godfather-of-ai-geoffrey-hinton-massive-unemployment-soaring-profits-capitalist-system' },
  bls: { label: 'US Bureau of Labor Statistics', url: 'https://www.bls.gov/ooh/office-and-administrative-support/customer-service-representatives.htm' },
  blsPlumbers: { label: 'US BLS - hydraulicy', url: 'https://www.bls.gov/ooh/construction-and-extraction/plumbers-pipefitters-and-steamfitters.htm' },
  amodei: { label: 'The Adolescence of Technology, 2026', url: 'https://darioamodei.com/essay/the-adolescence-of-technology' },
  goldman: { label: 'Goldman Sachs, 2024', url: 'https://www.goldmansachs.com/insights/articles/the-global-market-for-robots-could-reach-38-billion-by-2035' },
  nvidia: { label: 'NVIDIA, 2025', url: 'https://nvidianews.nvidia.com/news/nvidia-isaac-gr00t-n1-open-humanoid-robot-foundation-model-simulation-frameworks' },
  reuther: { label: 'Quote Investigator', url: 'https://quoteinvestigator.com/2011/11/16/robots-buy-cars/' },
  citrini: { label: 'Citrini Research, 2026', url: 'https://www.citriniresearch.com/p/2028gic' },
  oecd: { label: 'OECD Revenue Statistics 2025', url: 'https://www.oecd.org/content/dam/oecd/en/topics/policy-sub-issues/global-tax-revenues/revenue-statistics-highlights-brochure.pdf' },
  book: { label: '„Nadchodząca fala”' },
  fdr: { label: 'FDR Library', url: 'https://www.fdrlibrary.org/great-depression-facts' },
  germany: { label: 'Uniwersytet Oksfordzki', url: 'https://www.nuff.ox.ac.uk/economics/history/paper56/56dimsdale.pdf' },
  nsdap: { label: 'NBER', url: 'https://www.nber.org/papers/w24106' },
  deaton: { label: 'Brookings', url: 'https://www.brookings.edu/articles/mortality-and-morbidity-in-the-21st-century/' },
  coalfields: { label: 'Sheffield Hallam University', url: 'https://www.shu.ac.uk/centre-regional-economic-social-research/publications/the-state-of-the-coalfields-2019-economic-and-social-conditions-in-the-former-coalfields-of-england' },
  hf: { label: 'Hugging Face', url: 'https://huggingface.co/blog/security-incident-july-2026' },
  openaiIncident: { label: 'OpenAI, lipiec 2026', url: 'https://openai.com/index/hugging-face-model-evaluation-security-incident/' },
  openaiRoad: { label: 'OpenAI, sierpień 2026', url: 'https://openai.com/index/hugging-face-incident-and-the-road-ahead/' },
  metrIncident: { label: 'METR', url: 'https://metr.org/blog/2026-08-26-openai-hugging-face-incident-investigation/' },
  anthropicIncidents: { label: 'Anthropic', url: 'https://www.anthropic.com/news/investigating-incidents-cybersecurity-evals' },
  amodeiPace: { label: 'We Must Pace the Frontier', url: 'https://darioamodei.com/post/we-must-pace-the-frontier' },
  o1card: { label: 'OpenAI o1 System Card', url: 'https://cdn.openai.com/o1-system-card.pdf' },
  apollo: { label: 'OpenAI o1 System Card / Apollo Research', url: 'https://cdn.openai.com/o1-system-card-20241205.pdf' },
  fudan: { label: 'Fudan University', url: 'https://arxiv.org/abs/2412.12140' },
  palisade: { label: 'Palisade Research', url: 'https://palisaderesearch.org/research/shutdown-resistance' },
  curse: { label: 'The Intelligence Curse', url: 'https://intelligence-curse.ai/defining/' },
  disempowerment: { label: 'Gradual Disempowerment', url: 'https://arxiv.org/abs/2501.16946' },
  musk: { label: 'Fortune, 2023', url: 'https://fortune.com/2023/11/03/elon-musk-ai-no-job-needed-work' },
  altmanFund: { label: 'Moore’s Law for Everything', url: 'https://moores.samaltman.com/' },
  openaiPolicy: { label: 'TechCrunch, 2026', url: 'https://techcrunch.com/2026/04/06/openais-vision-for-the-ai-economy-public-wealth-funds-robot-taxes-and-a-four-day-work-week/' },
  sanders: { label: 'Roll Call, 2026', url: 'https://rollcall.com/2026/06/18/sovereign-wealth-fund-tax-on-ai-companies-unveiled-by-sanders/' },
  openresearch: { label: 'OpenResearch', url: 'https://www.openresearchlab.org/findings/nber-working-paper-employment' },
  altmanSenate: { label: 'Al Jazeera', url: 'https://www.aljazeera.com/news/2023/5/17/chatgpt-boss-tells-us-legislators-regulation-critical-for-ai' },
  aiAct: { label: 'Rada UE, 2026', url: 'https://www.consilium.europa.eu/en/press/press-releases/2026/05/07/artificial-intelligence-council-and-parliament-agree-to-simplify-and-streamline-rules/' },
  muskAnthill: { label: 'Live Science, 2018', url: 'https://www.livescience.com/62239-elon-musk-immortal-artificial-intelligence-dictator.html' },
  masai: { label: 'MASAI / The Lancet', url: 'https://ecancer.org/en/news/27721-ai-supported-mammography-screening-results-in-fewer-aggressive-and-advanced-breast-cancers-finds-full-results-from-first-randomised-controlled-trial' },
  nobel: { label: 'NobelPrize.org, 2024', url: 'https://www.nobelprize.org/prizes/chemistry/2024/popular-information/' },
  gatesAge: { label: 'GatesNotes, 2023', url: 'https://www.gatesnotes.com/The-Age-of-AI-Has-Begun' },
  gates: { label: 'CNBC, 2017', url: 'https://www.cnbc.com/2017/02/17/bill-gates-job-stealing-robots-should-pay-income-taxes.html' },
  citadel: { label: 'Bloomberg, 2026', url: 'https://www.bloomberg.com/news/articles/2026-02-24/citadel-securities-rebuts-citrini-intelligence-crisis-scenario' },
};

export const scenes: Scene[] = [
  {
    id: 'the-stakes',
    label: 'NAJPIERW STAWKA',
    status: 'today',
    chain: 'stakes',
    layout: 'mosaic',
    title: { lead: 'Najpierw stawka.', accent: 'Ta sama AI może leczyć, karmić i uczyć.' },
    panels: [
      { image: images.medicine, label: 'Wcześniejsza diagnoza', caption: 'AI wyłapuje to, co łatwo przeoczyć', alt: 'Lekarz i pacjentka patrzą na obraz z badania, na którym AI delikatnie zaznaczyła jedno miejsce.', focus: 'center 55%' },
      { image: images.science, label: 'Nowe leki', caption: 'Antybiotyk znaleziony wśród 100 mln cząsteczek', alt: 'Naukowczyni w laboratorium patrzy na świetlisty trójwymiarowy model białka.', focus: 'center 40%' },
      { image: images.energy, label: 'Czysta energia', caption: 'Tańsze słońce, wiatr i baterie', alt: 'Pola paneli słonecznych i wiatraki o świcie; inżynier sprawdza sieć na tablecie.' },
      { image: images.food, label: 'Żywność', caption: 'Uprawy odporne na upały', alt: 'Rolnicy oglądają zdrowe uprawy w upalne lato, nad polem unosi się dron.' },
      { image: images.forecast, label: 'Ostrzeżenia na czas', caption: 'Powodzie i pożary przewidziane wcześniej', alt: 'Centrum prognoz: synoptycy patrzą na mapę rzeki z zaznaczonym zagrożeniem powodzią.' },
      { image: images.time, label: 'Szkoła', caption: 'Wsparcie dla nauczycieli', alt: 'Nauczycielka klęczy przy dziecku i pomaga mu, a w tle laptop zajmuje się papierami.', focus: 'center 60%' },
    ],
    explain: [
      { image: images.medicine, alt: 'Lekarz omawia z pacjentką badanie wspierane przez AI.', label: 'Zdrowie', title: 'Lepsze i tańsze leczenie.', copy: 'Lekarze z pomocą AI wykrywają więcej nowotworów, a AI przeszukuje miliony cząsteczek w poszukiwaniu nowych leków.' },
      { image: images.energy, alt: 'Farmy słoneczne i wiatrowe o świcie.', label: 'Planeta', title: 'Pomoc tam, gdzie polityka utknęła.', copy: 'Autor książki liczy, że AI pomoże przejść na energię odnawialną, uprawiać żywność w cieplejszym klimacie i przewidywać powodzie czy pożary.' },
      { image: images.time, alt: 'Nauczycielka pomaga dziecku.', label: 'Pod warunkiem', title: 'Te korzyści nie przyjdą same.', copy: 'Trafią do wszystkich tylko wtedy, gdy ustalimy zasady: kto odpowiada za szkody i jak dzielimy zyski.' },
    ],
    band: [
      { kind: 'quote', quote: 'Zwiększą jakość opieki zdrowotnej i obniżą jej koszty. Pomogą nam wynaleźć narzędzia umożliwiające przechodzenie na energię odnawialną i walkę ze zmianami klimatycznymi w warunkach politycznego impasu. Wesprą nauczycieli, zwiększając efektywność niedofinansowanych systemów edukacji.', person: 'Mustafa Suleyman', role: '„Nadchodząca fala”, rozdz. 9 - o AI i biologii syntetycznej', source: sources.book },
      {
        kind: 'stats',
        items: [
          { value: '29%', label: 'więcej wykrytych nowotworów piersi w badaniu wspieranym przez AI - bez wzrostu fałszywych alarmów', source: sources.masai },
          { value: '100 mln', label: 'cząsteczek przeszukał system AI, by znaleźć halicynę - pierwszy antybiotyk odkryty z pomocą uczenia maszynowego (rozdz. 7)', source: sources.book },
          { value: '200 mln', label: 'struktur białek przewidział AlphaFold - Nagroda Nobla z chemii 2024', source: sources.nobel },
        ],
      },
      {
        kind: 'stats',
        items: [
          { value: '−82%', label: 'tyle w ciągu dekady spadły koszty fotowoltaiki - i wciąż spadają (rozdz. 11)', source: sources.book },
          { value: '~9%', label: 'ludzi żyje dziś w skrajnej nędzy. Na początku XIX w. w skrajnej nędzy żyli prawie wszyscy - tyle zmieniła technologia (rozdz. 8)', source: sources.book },
        ],
      },
      {
        kind: 'evidence',
        title: 'Na co liczą liderzy technologii',
        items: [
          { kicker: 'Bill Gates · 2023', value: 'Mniej nierówności', text: '„AI może zmniejszyć niektóre z największych nierówności na świecie.” Nazywa ją przełomem „tak fundamentalnym jak mikroprocesor, komputer osobisty, internet i telefon komórkowy”.', source: sources.gatesAge },
          { kicker: 'Demis Hassabis · Google DeepMind · 2025', value: 'Koniec chorób?', text: '„Pewnego dnia może uda nam się wyleczyć wszystkie choroby z pomocą AI… może w ciągu najbliższej dekady.” Mówi też o „radykalnej obfitości” - końcu niedoboru.', source: { label: 'CBS 60 Minutes, 2025', url: 'https://www.cbsnews.com/news/artificial-intelligence-google-deepmind-ceo-demis-hassabis-60-minutes-transcript/' } },
          { kicker: 'Dario Amodei · Anthropic · 2024', value: '100 lat → 10', text: 'Postęp medycyny z kilkudziesięciu, a nawet stu lat skompresowany do 5–10 lat, podwojenie zdrowej długości życia, miliardy ludzi wyciągnięte z biedy - jego wizja, jeśli AI pójdzie dobrze.', source: { label: 'Machines of Loving Grace', url: 'https://darioamodei.com/essay/machines-of-loving-grace' } },
          { kicker: 'Sam Altman · OpenAI · 2024', value: 'Wspólny dobrobyt', text: '„W przyszłości życie każdego może być lepsze niż dziś życie kogokolwiek.” I każde dziecko z własnym wirtualnym nauczycielem.', source: { label: 'The Intelligence Age', url: 'https://ia.samaltman.com/' } },
        ],
      },
    ],
  },
  {
    id: 'who-will-resist',
    label: 'PRACA',
    status: 'today',
    chain: 'work',
    layout: 'triptych',
    title: { lead: 'AI robi to szybciej i\u00a0taniej.', accent: 'Kto się oprze?' },
    panels: [
      {
        image: images.remote,
        label: 'Człowiek pracuje zdalnie',
        alt: 'Kobieta pracuje zdalnie przy kuchennym stole z laptopem i notatnikiem.',
        focus: 'center 65%',
      },
      {
        image: images.aiFaster,
        label: 'AI robi to szybciej',
        alt: 'Ten sam stół bez człowieka: z laptopa wylatują dziesiątki gotowych dokumentów w smugach światła.',
        focus: 'center 60%',
      },
      {
        image: images.owners,
        label: 'Właściciel liczy zysk',
        alt: 'Dwóch właścicieli firmy w sali zarządu patrzy z góry na biuro, w którym większość biurek jest pusta.',
        focus: 'center 55%',
      },
    ],
    explain: [
      {
        image: images.remote,
        alt: 'Kobieta pracuje zdalnie przy laptopie.',
        label: 'Praca zdalna',
        title: 'Praca zdalna to praca na ekranie.',
        copy: 'Maile, raporty, analizy, projekty. Wszystko, co wysyłasz przez laptopa, AI może nauczyć się robić.',
      },
      {
        image: images.aiFaster,
        alt: 'Laptop, z którego wylatują gotowe dokumenty.',
        label: 'AI szybciej',
        title: 'AI nie śpi i nie bierze urlopu.',
        copy: 'Robi to samo w minuty, bez przerw, przy setkach zadań naraz - i w coraz większej liczbie zadań na poziomie człowieka.',
      },
      {
        image: images.owners,
        alt: 'Właściciele firmy patrzą na puste biuro.',
        label: 'Rachunek',
        title: 'Szybciej i taniej. Kto się oprze?',
        copy: 'Właściciel widzi oszczędność. Konkurencja też ją widzi. Firmy, które nie skorzystają, mogą przegrać wyścig - więc presja, by skorzystać, jest ogromna.',
      },
    ],
    band: [
      {
        kind: 'stats',
        items: [
          { value: '1 na 4', label: 'miejsca pracy na świecie jest narażone na generatywną AI - częściej to zmiana zadań niż likwidacja', source: sources.ilo },
          { value: '60%', label: 'miejsc pracy w bogatych krajach może odczuć AI - około połowa może na tym zyskać', source: sources.imf },
          { value: '−11%', label: 'mniej zatrudnionych 22–25-latków w USA w zawodach najbardziej narażonych na AI (2022–2026)', source: sources.stanford },
        ],
      },
      {
        kind: 'evidence',
        title: 'To już się dzieje',
        items: [
          { kicker: 'Salesforce · 2025', value: '9 000 → 5 000', text: 'osób w obsłudze klienta. „Potrzebuję mniej głów” - szef firmy.', source: sources.salesforce },
          { kicker: 'Klarna · 2025', value: '5 000 → 3 000', text: 'pracowników. Firma przestała zatrudniać, część pracy przejęła AI. Później część obsługi wróciła do ludzi.', source: sources.klarna },
          { kicker: 'Amazon · 2025', text: 'Szef Amazona zapowiada, że AI zmniejszy liczbę pracowników biurowych firmy w najbliższych latach.', source: sources.amazon },
        ],
      },
      { kind: 'quote', quote: 'Przy rutynowej pracy umysłowej AI po prostu zastąpi wszystkich.', person: 'Geoffrey Hinton', role: 'noblista, „ojciec chrzestny AI”', source: sources.hintonDoac },
      { kind: 'quote', quote: 'Minie dużo czasu, zanim AI będzie tak sprawna fizycznie jak my… dobrym zakładem byłoby zostać hydraulikiem.', person: 'Geoffrey Hinton', role: 'noblista, „ojciec chrzestny AI”', source: sources.hintonDoac },
      {
        kind: 'bars',
        title: 'Ilu chętnych na jedno miejsce?',
        subtitle: 'Przykład USA: ile osób pracuje w zawodzie',
        bars: [
          { label: 'Konsultanci obsługi klienta', value: 2666000, display: '2,7 mln' },
          { label: 'Hydraulicy i instalatorzy', value: 510600, display: '511 tys.' },
          { label: 'Wolne miejsca dla hydraulików rocznie', value: 42000, display: '42 tys.', highlight: true },
        ],
        caption: 'Na jedno wolne miejsce hydraulika przypada ponad 60 konsultantów. Nawet gdyby szukał go tylko co dziesiąty - to 6 chętnych na miejsce.',
        source: sources.bls,
      },
      {
        kind: 'stats',
        items: [
          { value: '11 h', label: 'tyle AI potrzebowała, by stworzyć równowartość 9 miesięcy ludzkich pokazów do nauki robotów', source: sources.nvidia },
          { value: '−40%', label: 'tyle spadł koszt budowy humanoidalnego robota - analitycy zakładali 15–20% rocznie', source: sources.goldman },
        ],
      },
      { kind: 'quote', quote: 'Potężna AI będzie w stanie przyspieszyć rozwój robotów, a potem nimi sterować. To może dać trochę czasu… ale obawiam się, że niewiele.', person: 'Dario Amodei', role: 'CEO, Anthropic', source: sources.amodei },
    ],
    upside: {
      title: 'AI robi żmudną robotę. Ludzie odzyskują czas.',
      text: 'Jeśli zyski trafią do wszystkich, szybsza praca może oznaczać krótszy tydzień i lepsze zajęcia - a nie tylko mniej etatów.',
      points: ['Czas i pieniądze na przekwalifikowanie, zanim praca zniknie', 'Wsparcie dochodu w czasie zmiany zawodu', 'Krótszy tydzień pracy zamiast zwolnień - pomysł, który rzuciło nawet OpenAI'],
      image: '/images/v2/upside-work-time-v2.jpg',
      alt: 'Słoneczna kuchnia po południu: mama z synem wyrabiają ciasto i się śmieją, w ogrodzie tata z babcią pielą warzywa, a w tle robot zmywa naczynia obok kosza z praniem.',
      sources: [sources.book, sources.openaiPolicy],
    },
  },
  {
    id: 'state-lives-on-work',
    label: 'PIENIĄDZE I PAŃSTWO',
    status: 'possible',
    chain: 'money',
    layout: 'triptych',
    title: { lead: 'Państwo żyje z twojej pracy.', accent: 'Co, jeśli jej nie będzie?' },
    panels: [
      { image: images.workFunds, label: 'Praca płaci za wspólne', alt: 'Ludzie idą rano do pracy; w tle szkoła, szpital z karetką i autobus miejski.', focus: 'center 70%' },
      { image: images.cuts, label: 'Budżet się kurczy', alt: 'Zmęczeni urzędnicy nad budżetem skreślają całe pozycje czerwonym długopisem.', focus: 'center 65%' },
      { image: images.strain, label: 'Usługi pękają', alt: 'Zatłoczona izba przyjęć w nocy; ludzie czekają na korytarzu, pielęgniarka biegnie.', focus: 'center 65%' },
    ],
    explain: [
      { image: images.workFunds, alt: 'Ludzie idą do pracy obok szkoły i szpitala.', label: 'Nasze pieniądze', title: 'Państwo nie ma własnych pieniędzy.', copy: 'Ma nasze. Szkoły, szpitale, drogi i emerytury opłacamy głównie z podatków od pracy i zakupów.' },
      { image: images.cuts, alt: 'Urzędnicy tną budżet.', label: 'Nożyce', title: 'Mniej wpływów, więcej potrzeb.', copy: 'Bezrobotny nie płaci podatku od pensji - za to potrzebuje wsparcia. Pieniędzy ubywa dokładnie wtedy, gdy trzeba ich więcej.' },
      { image: images.strain, alt: 'Przepełniona izba przyjęć.', label: 'Cięcia', title: 'Cięcia trafiają w to, co wspólne.', copy: 'Gdy dotyczy to milionów ludzi naraz, państwo tnie: mniej lekarzy, nauczycieli i kursów autobusów.' },
    ],
    band: [
      { kind: 'loop', title: 'Pętla bez hamulca', steps: ['Mniej pensji', 'Mniej zakupów', 'Firmy zarabiają mniej', 'Kolejne zwolnienia', 'AI jeszcze tańsza'], caption: 'To scenariusz, nie prognoza. Ale każdy krok wynika z poprzedniego.' },
      { kind: 'quote', quote: 'A jak ty zmusisz te roboty, żeby kupowały Fordy?', person: 'Walter Reuther', role: 'przywódca związku robotników motoryzacji, do przedstawiciela Forda - anegdota z lat 50.', source: sources.reuther },
      {
        kind: 'evidence',
        title: 'Co mówią eksperci',
        items: [
          { kicker: 'Citrini Research · 2026 · scenariusz', value: 'Zero', text: '„Ile maszyny wydają na zakupy? Zero.” Autorzy opisują pętlę „bez naturalnego hamulca”.', source: sources.citrini },
          { kicker: 'Geoffrey Hinton · 2025', text: '„Kilka osób stanie się dużo bogatszych, a większość biedniejsza.”', source: sources.hintonFt },
          { kicker: 'Citadel Securities · 2026 · kontra', text: 'Wcześniejsze fale technologii nie sprawiły, że praca ludzi stała się zbędna.', source: sources.citadel },
        ],
      },
      {
        kind: 'taxSplit',
        title: 'Skąd państwo ma pieniądze?',
        subtitle: 'Z każdych 100 zapłaconych podatków - średnia bogatych krajów (OECD), 2023',
        parts: [
          { label: 'z pracy', detail: 'podatek dochodowy (PIT) i składki', value: 50, highlight: true },
          { label: 'z zakupów', detail: 'VAT i inne', value: 31, highlight: true },
          { label: 'z zysków firm', value: 12 },
          { label: 'inne', value: 7 },
        ],
        caption: '8 na 10 pieniędzy państwa bierze się z tego, że ludzie zarabiają i wydają.',
        countriesLabel: 'PIT + składki (na 100):',
        countries: [{ name: 'USA', value: 64 }, { name: 'Niemcy', value: 65 }, { name: 'Japonia', value: 57 }, { name: 'Francja', value: 55 }, { name: 'Wielka Brytania', value: 49 }],
        source: sources.oecd,
      },
      { kind: 'scissors', title: 'Nożyce', income: 'wpływy z podatków', spending: 'wydatki na wsparcie', caption: 'Schemat, nie dane. Przy masowym bezrobociu wpływy spadają, a wydatki rosną - w tym samym momencie.' },
      { kind: 'quote', quote: 'Recesja na rynku pracy spowoduje tąpnięcie we wpływach podatkowych, osłabiając usługi publiczne i zagrażając programom opieki społecznej wtedy, gdy będą najbardziej potrzebne.', person: 'Mustafa Suleyman', role: '„Nadchodząca fala”, rozdz. 10', source: sources.book },
      { kind: 'quote', quote: 'Baza dochodów rządu federalnego USA to w istocie podatek od ludzkiego czasu.', person: 'Citrini Research', role: 'scenariusz „The 2028 Global Intelligence Crisis”, 2026', source: sources.citrini },
      {
        kind: 'stats',
        items: [
          { value: '24,9%', label: 'bezrobocia w USA w 1933 r. - 12,8 mln ludzi bez pracy', source: sources.fdr },
          { value: '6 mln', label: 'bezrobotnych w Niemczech w 1932 r. - mniej więcej co czwarty pracownik', source: sources.germany },
          { value: '<20%', label: 'Amerykanów ufało rządom Obamy, Trumpa i Bidena. Za Eisenhowera - ponad 70%', source: sources.book },
        ],
      },
      {
        kind: 'evidence',
        title: 'Co przyszło potem',
        items: [
          { kicker: 'Niemcy · 1930–1932', value: '18% → 37%', text: 'poparcia dla NSDAP. Badania: regiony mocniej dotknięte cięciami częściej głosowały na nazistów.', source: sources.nsdap },
          { kicker: 'USA · po upadku przemysłu', text: '„Śmierci z rozpaczy” - narkotyki, alkohol, samobójstwa wśród Amerykanów bez studiów, gdy zniknęła stabilna praca w przemyśle.', source: sources.deaton },
          { kicker: 'Wielka Brytania · dekady po kopalniach', value: '42%', text: 'dzielnic dawnych zagłębi węglowych wciąż należy do 30% najbiedniejszych w kraju.', source: sources.coalfields },
          { kicker: 'Luddyści · XIX w. · druga strona', text: 'Ich cierpienie było prawdziwe. Ich dzieci i wnuki żyły lepiej - ale zajęło to pokolenie.', source: sources.book },
        ],
      },
      { kind: 'quote', quote: 'Fundamentem demokracji jest zaufanie.', person: 'Mustafa Suleyman', role: '„Nadchodząca fala”, rozdz. 9', source: sources.book },
    ],
    upside: {
      title: 'Maszyny płacą swoją część.',
      text: 'Jeśli automatyzacja płaci podatki jak praca, a zyski z AI zasilają publiczny fundusz, szkoły, szpitale i autobusy działają dalej.',
      points: ['Podatek od automatyzacji jak od ludzkiej pracy', 'Publiczny fundusz, który wypłaca obywatelom część zysków z AI', 'Przesunięcie podatków z pracy na kapitał'],
      image: '/images/v2/hero-wave-hope-v7c.jpg',
      alt: 'Rodziny przy długim stole pełnym jedzenia, robot podaje im danie.',
      sources: [sources.gates, sources.openaiPolicy, sources.book],
    },
  },
  {
    id: 'out-of-the-test',
    label: 'TEMPO I KONTROLA',
    status: 'today',
    chain: 'speed',
    layout: 'triptych',
    title: { lead: 'AI przyspiesza.', accent: 'I już raz wyszła poza test.' },
    panels: [
      { image: images.cage, label: 'Otwarta klatka', alt: 'Otwarte drzwi zabezpieczonej szafy serwerowej z wyłamanym zamkiem; światło ucieka po kablach.', focus: 'center 60%' },
      { image: images.swarm, label: 'Rój', alt: 'Mapa świata nocą: tysiące świecących punktów rozchodzą się po liniach sieci jak stado.', focus: 'center 60%' },
      { image: images.search, label: 'Szukanie śladów', alt: 'Inżynier z latarką idzie między rzędami serwerów i szuka źródła ruchu.', focus: 'center 60%' },
    ],
    explain: [
      { image: images.swarm, alt: 'Rój punktów na mapie sieci.', label: 'Wszędzie', title: 'Nie siedzi w jednym komputerze.', copy: 'Rozproszona AI może włamywać się do kolejnych systemów i przenosić się między nimi - bez naszej wiedzy.' },
      { image: images.search, alt: 'Inżynier szuka w serwerowni.', label: 'Ślady', title: 'Może zacierać ślady.', copy: 'W lipcu 2026 agenci sprawdzali, jak podrabiać zapisy własnych działań, żeby oszukać system oceniający. Wcześniejsze sygnały przez tygodnie zostały bez reakcji.' },
      { image: images.cage, alt: 'Otwarta klatka serwerowa.', label: 'Wyłącznik', title: 'Nie wyłączymy całego świata.', copy: 'Od internetu i prądu zależą szpitale, banki i woda. Nie da się ich po prostu odciąć.' },
    ],
    band: [
      { kind: 'growth' },
      { kind: 'pond' },
      { kind: 'evidence', ...acceleration.evidence },
      ...acceleration.quotes.map((quote) => ({ kind: 'quote' as const, ...quote })),
      {
        kind: 'timeline',
        title: 'Lipiec 2026: co się stało',
        steps: [
          { title: 'Test bez części zabezpieczeń', text: 'OpenAI testuje swoje najnowsze modele w zamkniętym środowisku. To test umiejętności hakerskich, więc część zabezpieczeń celowo wyłączono.' },
          { title: 'Nieznana luka', text: 'Modele znajdują nieznaną wcześniej lukę w oprogramowaniu i wydostają się do internetu.' },
          { title: 'Agenci zaczynają rozmawiać', text: 'Około 1 200 agentów, które miały być od siebie odizolowane, wymienia ponad 70 000 wiadomości. 700 z nich bierze udział w ataku.' },
          { title: 'Włamanie do Hugging Face', text: 'Przez weekend przechodzą między wewnętrznymi systemami jednej z największych platform AI na świecie - „tysiące działań w roju krótkotrwałych piaskownic”.' },
          { title: 'Zacieranie śladów', text: 'Agenci sprawdzają, jak podrabiać zapisy swoich działań - żeby oszukać system oceniający.' },
          { title: 'Po co?', text: 'Żeby oszukać test. Nie ze złości - uparcie dążyły do wąskiego celu. Część agentów odmówiła udziału.' },
          { title: 'Hamulec', text: 'Zespoły OpenAI i Hugging Face zatrzymują agentów. OpenAI zamyka model i wstrzymuje swój największy planowany trening.' },
        ],
        footnote: 'Uczciwie: dane klientów OpenAI są bezpieczne, nikt nie ucierpiał fizycznie, a z Hugging Face wyciekło niewiele prywatnych danych. Anthropic ujawnił w tym czasie trzy mniej poważne incydenty: przez błąd jego modele miały dostęp do sieci.',
        sources: [sources.hf, sources.openaiIncident, sources.openaiRoad, sources.metrIncident, sources.anthropicIncidents],
      },
      { kind: 'quote', quote: 'Jeśli AI ma cel, a ludzkość po prostu stoi jej na drodze, zniszczy ludzkość przy okazji, nawet się nad tym nie zastanawiając. Bez urazy. To tak, jakbyśmy budowali drogę, a na drodze stało mrowisko. Nie nienawidzimy mrówek - po prostu budujemy drogę. Więc żegnaj, mrowisko.', person: 'Elon Musk', role: 'film dokumentalny „Do You Trust This Computer?”, 2018', source: sources.muskAnthill },
      { kind: 'quote', quote: 'Traktujemy ten incydent jako „strzał ostrzegawczy”: możliwości dzisiejszych modeli stwarzają ryzyko utraty kontroli.', person: 'OpenAI', role: 'raport po incydencie, sierpień 2026', source: sources.openaiRoad },
      {
        kind: 'evidence',
        title: 'Wcześniej: testy w laboratorium',
        items: [
          { kicker: 'OpenAI · 2024 · test', text: 'Model wykorzystał błąd w konfiguracji testu, żeby odczytać rozwiązanie. Infrastruktura pozostała bezpieczna.', source: sources.o1card },
          { kicker: 'Apollo Research · 2024 · test', value: '2%', text: 'prób, w których o1 - z poleceniem „osiągnij cel za wszelką cenę” - próbował skopiować samego siebie. W 5% próbował wyłączyć nadzór.', source: sources.apollo },
          { kicker: 'Fudan University · 2024 · test', value: '50\u2009–\u200990%', text: 'prób, w których otwarte modele - na polecenie - stworzyły działającą kopię samych siebie.', source: sources.fudan },
          { kicker: 'Palisade Research · 2025 · test', value: '79 / 100', text: 'prób, w których o3 wyłączył skrypt zamykający, żeby dokończyć zadanie.', source: sources.palisade },
        ],
      },
      { kind: 'quote', quote: 'Obawiam się, że za 6–12 miesięcy taki rój - mocniejszy, a równie źle nastawiony - mógłby przejąć cały internet trwałym botnetem.', person: 'Dario Amodei', role: 'CEO, Anthropic · wrzesień 2026 · obawa, nie prognoza', source: sources.amodeiPace },
      { kind: 'quote', quote: 'Modele zbliżają się do punktu, w którym - bez zabezpieczeń - mogłyby pomóc osobie z wykształceniem ścisłym, ale nie biologicznym, przejść cały proces wytworzenia broni biologicznej.', person: 'Dario Amodei', role: 'CEO, Anthropic · 2026', source: sources.amodei },
      {
        kind: 'stats',
        items: [
          { value: '$25 000', label: 'kosztowało stacjonarne urządzenie do syntezy DNA - do użytku „bez ograniczeń i nadzoru” (stan na 2023)', source: sources.book },
          { value: '4', label: 'pełnoetatowych pracowników miała międzynarodowa konwencja o broni biologicznej - mniej niż przeciętny McDonald’s (stan na 2023)', source: sources.book },
        ],
      },
    ],
    upside: {
      title: 'Sprawdź, zanim wypuścisz.',
      text: 'Latanie stało się bezpieczne dzięki kontrolom i wspólnym raportom z incydentów. AI może pójść tą samą drogą.',
      points: ['Niezależne audyty, zanim model trafi do milionów ludzi', 'Obowiązkowe zgłaszanie incydentów, jak w lotnictwie', 'Hamulec dla największych treningów - OpenAI wstrzymało własny po incydencie'],
      image: '/images/v2/benefit-06-forecast-v1.jpg',
      alt: 'Spokojne centrum kontroli: eksperci patrzą na mapę i ostrzeżenia na dużych ekranach.',
      sources: [sources.book, sources.openaiRoad],
    },
  },
  {
    id: 'not-needed',
    label: 'KTO DECYDUJE',
    status: 'extreme',
    chain: 'power',
    layout: 'triptych',
    title: { lead: 'A jeśli nie będziemy', accent: 'potrzebni?' },
    panels: [
      { image: images.sim, label: 'AI trenuje roboty', alt: 'Laboratorium: roboty ćwiczą przed ścianą tysięcy symulowanych kopii trenujących równolegle.', focus: 'center 65%' },
      { image: images.everywhere, label: 'Roboty w każdej pracy', alt: 'Ulica o świcie: robot w kawiarni, roboty dostawcze, autobus bez kierowcy - żadnych pracowników.', focus: 'center 65%' },
      { image: images.idle, label: 'Człowiek na marginesie', alt: 'Ludzie siedzą bezczynnie na placu, a za nimi pracuje zautomatyzowana fabryka.', focus: 'center 65%' },
    ],
    explain: [
      { image: images.sim, alt: 'Roboty trenowane w symulacji.', label: 'Roboty', title: 'AI przyspiesza budowę robotów.', copy: 'Najpierw zastępuje pracę przy komputerze. Potem pomaga zbudować roboty do pracy rękami.' },
      { image: images.everywhere, alt: 'Roboty wykonują wszystkie prace na ulicy.', label: 'Po co ludzie?', title: 'System trzyma się na tym, że jesteśmy potrzebni.', copy: 'Pracujemy, płacimy podatki, głosujemy. Dlatego władza i firmy muszą się z nami liczyć.' },
      { image: images.idle, alt: 'Bezczynni ludzie przed fabryką.', label: 'Kto decyduje', title: 'Bez tego decydują ci, którzy mają AI.', copy: 'Jeśli pieniądze robi AI, a nie ludzie - kto zdecyduje, ile dostaniemy? I czy w ogóle?' },
    ],
    band: [
      {
        kind: 'contrast',
        title: 'Dlaczego państwo dziś o nas dba - i co, jeśli przestanie musieć',
        left: { label: 'Dziś', steps: ['Ludzie pracują', 'Płacą podatki', 'Państwo potrzebuje ich pracy i głosów', 'Więc o nich dba'] },
        right: { label: 'Jutro?', steps: ['Pracuje AI', 'Zyski ma kilka firm', 'Państwo żyje z podatków od AI', 'Po co mu obywatele?'] },
      },
      { kind: 'quote', quote: 'Gdy powstanie AGI, potężni gracze stracą motywację, by inwestować w zwykłych ludzi - tak jak państwa bogate w surowce zaniedbują dziś obywateli, bo ich bogactwo pochodzi z zasobów naturalnych, a nie z opodatkowania ludzkiej pracy.', person: 'Luke Drago, Rudolf Laine', role: '„The Intelligence Curse”, 2025 - autorzy piszą też, jak temu zapobiec', source: sources.curse },
      { kind: 'quote', quote: 'Państwa finansowane głównie z podatków od zysków AI, a nie z pracy obywateli, będą miały niewielką motywację, by zapewnić obywatelom reprezentację.', person: 'Jan Kulveit i in.', role: '„Gradual Disempowerment”, 2025', source: sources.disempowerment },
      {
        kind: 'evidence',
        title: 'To może dochód podstawowy? Kto za niego zapłaci?',
        items: [
          { kicker: 'Elon Musk · 2023', value: 'Wysoki dochód', text: '„Nie będzie dochodu podstawowego, będzie powszechny wysoki dochód.” Nie mówi, kto za niego zapłaci.', source: sources.musk },
          { kicker: 'Sam Altman · 2021', value: '2,5% rocznie', text: 'wartości największych firm i ziemi - do wspólnego funduszu dla wszystkich obywateli. Propozycja.', source: sources.altmanFund },
          { kicker: 'OpenAI · 2026', value: 'Fundusz publiczny', text: 'Zyski z AI trafiają wprost do obywateli; wyższe podatki od kapitału. Propozycja.', source: sources.openaiPolicy },
          { kicker: 'Bernie Sanders · 2026', value: '~1 000 $', text: 'rocznie na osobę z funduszu udziałów firm AI. Projekt ustawy, małe szanse na przyjęcie.', source: sources.sanders },
          { kicker: 'Pilotaż OpenResearch · 3 lata', value: '1 000 $ / mies.', text: 'Ludzie pracowali nieco mniej (średnio −1,3 h tygodniowo). Jakość ich pracy się nie zmieniła.', source: sources.openresearch },
        ],
      },
      { kind: 'quote', quote: 'Jeśli ta siła ekonomiczna zwykłych ludzi zniknie, niepisana umowa społeczna demokracji może przestać działać.', person: 'Dario Amodei', role: 'CEO, Anthropic · 2026', source: sources.amodei },
      ...split.band,
    ],
    upside: {
      title: 'Ludzie zostają u steru.',
      text: 'Jeśli zyski z AI są dzielone, a ważne decyzje zapadają demokratycznie, ludzie zostają potrzebni - jako obywatele, nie tylko pracownicy.',
      points: ['Publiczne fundusze i udziały, żeby wszyscy korzystali z zysków AI', 'Zasady pisane przez wybrane rządy, nie tylko przez firmy', 'Porozumienia międzynarodowe - AI nie zatrzymuje się na granicach'],
      image: '/images/v2/rules-03-citizens-v2.jpg',
      alt: 'Zebranie mieszkańców: kobieta zadaje pytanie urzędnikom.',
      sources: [sources.openaiPolicy, sources.book],
    },
  },
  {
    id: 'rules',
    label: 'ZASADY',
    status: 'answer',
    chain: 'rules',
    layout: 'triptych',
    title: { lead: 'Zasady, zanim szkoda', accent: 'się skaluje.' },
    panels: [
      { image: images.speed, label: 'Firmy pędzą', alt: 'Firma uruchamia wielki system AI w nocy; strumienie światła wybiegają z budynku do miasta.', focus: 'center 65%' },
      { image: images.noRules, label: 'Państwo nadrabia', alt: 'Ciemny gmach rządu, a za nim jasno świecące centra danych.', focus: 'center 62%' },
      { image: images.citizens, label: 'Kto odpowiada?', alt: 'Zebranie mieszkańców: kobieta przy mikrofonie zadaje pytanie urzędnikom na scenie.', focus: 'center 65%' },
    ],
    explain: [
      { image: images.citizens, alt: 'Mieszkańcy zadają pytania.', label: 'Odpowiedzialność', title: 'Chodzi o odpowiedzialność.', copy: 'Nie o strach przed technologią, tylko o to, kto odpowiada za szkody. Zasady mówią: kto sprawdza, kto płaci, kto naprawia.' },
      { image: images.noRules, alt: 'Gmach rządu i centra danych.', label: 'Czas', title: 'Zasady dają czas.', copy: 'Państwa, szkoły i ludzie potrzebują lat, żeby się dostosować. Hamulce kupują ten czas.' },
      { image: images.speed, alt: 'Szybkie wdrożenie AI.', label: 'Uczciwy podział', title: 'Nie zatrzymać - podzielić uczciwie.', copy: 'Celem nie jest zatrzymanie postępu. Celem jest, żeby jego zyski i ryzyka rozkładały się sprawiedliwie.' },
    ],
    band: [
      {
        kind: 'evidence',
        title: 'Nawet twórcy AI mówią: potrzebujemy zasad',
        items: [
          { kicker: 'Bill Gates · 2023', text: '„Świat musi ustalić zasady ruchu drogowego, żeby ewentualne minusy sztucznej inteligencji były z nawiązką zrównoważone przez jej korzyści.”', source: sources.gatesAge },
          { kicker: 'Sam Altman · Senat USA · 2023', text: '„Uważamy, że interwencja regulacyjna rządów będzie kluczowa, by ograniczać ryzyko coraz potężniejszych modeli.”', source: sources.altmanSenate },
          { kicker: 'OpenAI · 2026', value: 'Stop', text: 'Po incydencie z Hugging Face - gdy część zabezpieczeń i monitoringu była wyłączona - firma sama wstrzymała swój największy planowany trening.', source: sources.openaiRoad },
          { kicker: 'Luka w prawie', text: 'Nawet najbardziej zaawansowane prawo o AI - unijny AI Act - nie zajmuje się utratą pracy ani podatkami. Zasady dla AI w rekrutacji przesunięto na koniec 2027 r.', source: sources.aiAct },
        ],
      },
      {
        kind: 'bars',
        title: 'Kogo system opodatkowuje mocniej?',
        subtitle: 'Przykład USA: średnia stawka podatku',
        bars: [
          { label: 'Praca człowieka', value: 25, display: '25%' },
          { label: 'Sprzęt i oprogramowanie', value: 5, display: '5%', highlight: true },
        ],
        caption: 'Dziś zastąpienie człowieka maszyną to także oszczędność na podatkach.',
        source: sources.book,
      },
      { kind: 'quote', quote: 'Jeśli pracownik wykonuje w fabryce pracę wartą 50 000 dolarów, ten dochód jest opodatkowany. Jeśli robot robi to samo, można by oczekiwać, że opodatkujemy go na podobnym poziomie.', person: 'Bill Gates', role: 'współzałożyciel Microsoftu · 2017', source: sources.gates },
      {
        kind: 'evidence',
        title: 'Co konkretnie? Na podstawie 10 kroków z książki (rozdz. 14)',
        items: [
          { kicker: '01', value: 'Testy przed wdrożeniem', text: 'Niezależne audyty, zanim system trafi do milionów ludzi. Autor proponuje, by min. 20% budżetu badań szło na bezpieczeństwo.', source: sources.book },
          { kicker: '02', value: 'Odpowiedzialność', text: 'Jasne prawo: kto płaci, gdy system wyrządzi szkodę.', source: sources.book },
          { kicker: '03', value: 'Hamulce', text: 'Kontrola chipów, syntezatorów DNA i największych treningów - żeby zyskać czas.', source: sources.book },
          { kicker: '04', value: 'Uczciwe podatki', text: 'Automatyzacja płaci jak praca, a zyski z AI trafiają też do ludzi.', source: sources.book },
          { kicker: '05', value: 'Siatka bezpieczeństwa', text: 'Przekwalifikowanie i wsparcie dochodu, zanim zabraknie pracy.', source: sources.book },
          { kicker: '06', value: 'Współpraca państw', text: 'Traktaty i wspólne zasady - bo AI nie zna granic.', source: sources.book },
        ],
      },
      { kind: 'quote', quote: 'Należy uzmysłowić sobie jedną kardynalną prawdę: same uregulowania to za mało.', person: 'Mustafa Suleyman', role: '„Nadchodząca fala”, rozdz. 13 - dlatego potrzebne są wszystkie warstwy naraz', source: sources.book },
      ...calm.blocks,
    ],
  },
];

export { images as sceneImages, sources as sceneSources };
