import type { Scene } from '../../types/scene.types';

const images = {
  layoffs: '/images/v2/threat-02-layoffs-v1.jpg',
  aiRules: '/images/v2/threat-02-ai-rules-v1.jpg',
  bio: '/images/v2/threat-03-bio-v1.jpg',
  remote: '/images/v2/work-01-remote-v1.jpg',
  aiFaster: '/images/v2/work-02-ai-faster-v2.jpg',
  owners: '/images/v2/work-03-owners-v1.jpg',
  callcenter: '/images/v2/jobs-01-callcenter-v1.jpg',
  legal: '/images/v2/jobs-02-legal-v1.jpg',
  design: '/images/v2/jobs-03-design-v1.jpg',
  translator: '/images/v2/jobs-04-translator-v1.jpg',
  warehouse: '/images/v2/jobs-05-warehouse-v1.jpg',
  driver: '/images/v2/jobs-06-driver-v1.jpg',
  queue: '/images/v2/trades-01-queue-v1.jpg',
  tooMany: '/images/v2/trades-02-too-many-v1.jpg',
  robot: '/images/v2/trades-03-robot-v1.jpg',
  bills: '/images/v2/demand-01-bills-v1.jpg',
  emptyStore: '/images/v2/demand-02-empty-store-v1.jpg',
  closing: '/images/v2/demand-03-closing-v1.jpg',
  workFunds: '/images/v2/state-01-work-funds-v1.jpg',
  cuts: '/images/v2/state-02-cuts-v1.jpg',
  strain: '/images/v2/state-03-strain-v1.jpg',
  depression: '/images/v2/history-01-depression-v1.jpg',
  factory: '/images/v2/history-02-factory-v1.jpg',
  anger: '/images/v2/history-03-anger-v1.jpg',
  cage: '/images/v2/breach-01-cage-v1.jpg',
  swarm: '/images/v2/breach-02-swarm-v1.jpg',
  search: '/images/v2/breach-03-search-v1.jpg',
  sim: '/images/v2/useless-01-sim-v1.jpg',
  everywhere: '/images/v2/useless-02-everywhere-v1.jpg',
  idle: '/images/v2/useless-03-idle-v1.jpg',
  speed: '/images/v2/rules-01-speed-v1.jpg',
  noRules: '/images/v2/threat-03-no-rules-v1.jpg',
  citizens: '/images/v2/rules-03-citizens-v2.jpg',
};

const sources = {
  ilo: { label: 'ILO–NASK, 2025', url: 'https://www.ilo.org/resource/news/one-four-jobs-risk-being-transformed-genai-new-ilo%E2%80%93nask-global-index-shows' },
  imf: { label: 'MFW, 2024', url: 'https://www.cnbc.com/2024/01/15/imf-warns-ai-to-hit-almost-40percent-of-global-employment-worsen-inequality.html' },
  stanford: { label: 'Stanford, 2026', url: 'https://digitaleconomy.stanford.edu/news/canariesaug26/' },
  salesforce: { label: 'CNBC', url: 'https://www.cnbc.com/2025/09/02/salesforce-ceo-confirms-4000-layoffs-because-i-need-less-heads-with-ai.html' },
  klarna: { label: 'CNBC', url: 'https://www.cnbc.com/2025/05/14/klarna-ceo-says-ai-helped-company-shrink-workforce-by-40percent.html' },
  amazon: { label: 'Amazon', url: 'https://www.aboutamazon.com/news/company-news/amazon-ceo-andy-jassy-on-generative-ai' },
  hintonDoac: { label: 'Diary of a CEO, 2025', url: 'https://singjupost.com/transcript-of-godfather-of-ai-i-tried-to-warn-them-but-weve-already-lost-control/' },
  hintonFt: { label: 'Financial Times / Fortune, 2025', url: 'https://fortune.com/2025/09/06/godfather-of-ai-geoffrey-hinton-massive-unemployment-soaring-profits-capitalist-system' },
  bls: { label: 'US Bureau of Labor Statistics', url: 'https://www.bls.gov/ooh/construction-and-extraction/plumbers-pipefitters-and-steamfitters.htm' },
  amodei: { label: 'The Adolescence of Technology, 2026', url: 'https://darioamodei.com/essay/the-adolescence-of-technology' },
  goldman: { label: 'Goldman Sachs, 2024', url: 'https://www.goldmansachs.com/insights/articles/the-global-market-for-robots-could-reach-38-billion-by-2035' },
  nvidia: { label: 'NVIDIA, 2025', url: 'https://nvidianews.nvidia.com/news/nvidia-isaac-gr00t-n1-open-humanoid-robot-foundation-model-simulation-frameworks' },
  reuther: { label: 'Quote Investigator', url: 'https://quoteinvestigator.com/2011/11/16/robots-buy-cars/' },
  citrini: { label: 'Citrini Research, 2026', url: 'https://www.citriniresearch.com/p/2028gic' },
  oecd: { label: 'OECD Revenue Statistics 2025', url: 'https://www.oecd.org/content/dam/oecd/en/topics/policy-sub-issues/global-tax-revenues/revenue-statistics-highlights-brochure.pdf' },
  book: { label: '„Nadchodząca fala”' },
  fdr: { label: 'FDR Library', url: 'https://www.fdrlibrary.org/great-depression-facts' },
  germany: { label: 'Uniwersytet Oksfordzki', url: 'https://www.nuff.ox.ac.uk/economics/history/paper56/56dimsdale.pdf' },
  nsdap: { label: 'NBER', url: 'https://www.nber.org/papers/w24106' },
  deaton: { label: 'Brookings', url: 'https://www.brookings.edu/articles/mortality-and-morbidity-in-the-21st-century/' },
  coalfields: { label: 'Sheffield Hallam University', url: 'https://www.shu.ac.uk/centre-regional-economic-social-research/publications/the-state-of-the-coalfields-2019-economic-and-social-conditions-in-the-former-coalfields-of-england' },
  hf: { label: 'Hugging Face', url: 'https://huggingface.co/blog/security-incident-july-2026' },
  openaiIncident: { label: 'OpenAI, lipiec 2026', url: 'https://openai.com/index/hugging-face-model-evaluation-security-incident/' },
  openaiRoad: { label: 'OpenAI, sierpień 2026', url: 'https://openai.com/index/hugging-face-incident-and-the-road-ahead/' },
  metrIncident: { label: 'METR', url: 'https://metr.org/blog/2026-08-26-openai-hugging-face-incident-investigation/' },
  anthropicIncidents: { label: 'Anthropic', url: 'https://www.anthropic.com/news/investigating-incidents-cybersecurity-evals' },
  amodeiPace: { label: 'We Must Pace the Frontier', url: 'https://darioamodei.com/post/we-must-pace-the-frontier' },
  o1card: { label: 'OpenAI o1 System Card', url: 'https://cdn.openai.com/o1-system-card.pdf' },
  apollo: { label: 'Apollo Research', url: 'https://www.apolloresearch.ai/research/scheming-reasoning-evaluations' },
  fudan: { label: 'Fudan University', url: 'https://arxiv.org/abs/2412.12140' },
  palisade: { label: 'Palisade Research', url: 'https://palisaderesearch.org/research/shutdown-resistance' },
  curse: { label: 'The Intelligence Curse', url: 'https://intelligence-curse.ai/defining/' },
  disempowerment: { label: 'Gradual Disempowerment', url: 'https://arxiv.org/abs/2501.16946' },
  musk: { label: 'Fortune, 2023', url: 'https://fortune.com/2023/11/03/elon-musk-ai-no-job-needed-work' },
  altmanFund: { label: 'Moore’s Law for Everything', url: 'https://moores.samaltman.com/' },
  openaiPolicy: { label: 'TechCrunch, 2026', url: 'https://techcrunch.com/2026/04/06/openais-vision-for-the-ai-economy-public-wealth-funds-robot-taxes-and-a-four-day-work-week/' },
  sanders: { label: 'Roll Call, 2026', url: 'https://rollcall.com/2026/06/18/sovereign-wealth-fund-tax-on-ai-companies-unveiled-by-sanders/' },
  openresearch: { label: 'OpenResearch', url: 'https://www.openresearchlab.org/findings/nber-working-paper-employment' },
  altmanSenate: { label: 'Al Jazeera', url: 'https://www.aljazeera.com/news/2023/5/17/chatgpt-boss-tells-us-legislators-regulation-critical-for-ai' },
  aiAct: { label: 'Rada UE, 2026', url: 'https://www.consilium.europa.eu/en/press/press-releases/2026/05/07/artificial-intelligence-council-and-parliament-agree-to-simplify-and-streamline-rules/' },
  gates: { label: 'CNBC, 2017', url: 'https://www.cnbc.com/2017/02/17/bill-gates-job-stealing-robots-should-pay-income-taxes.html' },
  citadel: { label: 'Bloomberg, 2026', url: 'https://www.bloomberg.com/news/articles/2026-02-24/citadel-securities-rebuts-citrini-intelligence-crisis-scenario' },
};

export const scenes: Scene[] = [
  {
    id: 'zagrozenia',
    number: '01',
    label: 'CO MOŻE PÓJŚĆ NIE TAK',
    status: 'MOŻLIWE SCENARIUSZE',
    layout: 'triptych',
    title: { lead: 'Trzy ryzyka.', accent: 'Żadnego hamulca.' },
    panels: [
      {
        image: images.layoffs,
        label: 'Fala zwolnień',
        alt: 'Długa kolejka pracowników biurowych wychodzi w deszczu z biurowca, niosąc kartony z rzeczami.',
        focus: 'center 70%',
      },
      {
        image: images.aiRules,
        label: 'AI przejmuje kontrolę',
        alt: 'Tysiące ludzi stoją w równych rzędach na placu pod ogromną maszyną, która skanuje ich wiązkami światła.',
        focus: 'center 60%',
      },
      {
        image: images.bio,
        label: 'Wirus z laboratorium',
        alt: 'Puste laboratorium: automatyczne ramię trzyma świecącą fiolkę, nad stołem model wirusa i przepisywanej helisy DNA.',
        focus: 'center 60%',
      },
    ],
    explain: [
      {
        image: images.layoffs,
        alt: 'Zwolnieni pracownicy wychodzą z biurowca z kartonami.',
        label: 'Zwolnienia',
        title: 'Praca znika szybciej, niż powstaje nowa.',
        copy: 'Jeśli AI robi to samo taniej, firmy mogą potrzebować mniej ludzi. Przebranżowienie trwa latami, rachunki przychodzą co miesiąc.',
      },
      {
        image: images.aiRules,
        alt: 'Ludzie w rzędach pod maszyną, która ich skanuje.',
        label: 'Kontrola',
        title: 'Decyzje przechodzą do maszyn.',
        copy: 'Kredyt, praca, leczenie, bezpieczeństwo. Im więcej decyzji oddajemy systemom, których nie rozumiemy, tym trudniej je potem odebrać.',
      },
      {
        image: images.bio,
        alt: 'Automatyczne laboratorium z modelem wirusa.',
        label: 'Biologia',
        title: 'Projektowanie życia tanieje.',
        copy: 'AI przyspiesza badania nad lekami — ale te same narzędzia mogą pomóc stworzyć groźny patogen. Wystarczy jeden błąd albo jedna zła intencja.',
      },
    ],
  },
  {
    id: 'praca',
    number: '02',
    label: 'JAK TO SIĘ ZACZYNA',
    status: 'DZIŚ',
    chain: 'praca',
    layout: 'triptych',
    title: { lead: 'AI robi to szybciej i\u00a0taniej.', accent: 'Kto się oprze?' },
    panels: [
      {
        image: images.remote,
        label: 'Człowiek pracuje zdalnie',
        alt: 'Kobieta pracuje zdalnie przy kuchennym stole z laptopem i notatnikiem.',
        focus: 'center 65%',
      },
      {
        image: images.aiFaster,
        label: 'AI robi to szybciej',
        alt: 'Ten sam stół bez człowieka: z laptopa wylatują dziesiątki gotowych dokumentów w smugach światła.',
        focus: 'center 60%',
      },
      {
        image: images.owners,
        label: 'Właściciel liczy zysk',
        alt: 'Dwóch właścicieli firmy w sali zarządu patrzy z góry na biuro, w którym większość biurek jest pusta.',
        focus: 'center 55%',
      },
    ],
    explain: [
      {
        image: images.remote,
        alt: 'Kobieta pracuje zdalnie przy laptopie.',
        label: 'Praca zdalna',
        title: 'Praca zdalna to praca na ekranie.',
        copy: 'Maile, raporty, analizy, projekty. Wszystko, co wysyłasz przez laptopa, AI może nauczyć się robić.',
      },
      {
        image: images.aiFaster,
        alt: 'Laptop, z którego wylatują gotowe dokumenty.',
        label: 'AI szybciej',
        title: 'AI nie śpi i nie bierze urlopu.',
        copy: 'Robi to samo w minuty, bez przerw, przy setkach zadań naraz — i w coraz większej liczbie zadań na poziomie człowieka.',
      },
      {
        image: images.owners,
        alt: 'Właściciele firmy patrzą na puste biuro.',
        label: 'Rachunek',
        title: 'Szybciej i taniej. Kto się oprze?',
        copy: 'Właściciel widzi oszczędność. Konkurencja też ją widzi. Firma, która nie skorzysta, przegra wyścig — więc skorzystają prawie wszyscy.',
      },
    ],
  },

  {
    id: 'zawody',
    number: '03',
    label: 'KTO JEST NASTĘPNY',
    status: 'DZIŚ',
    chain: 'praca',
    layout: 'mosaic',
    title: { lead: 'Nie tylko kod.', accent: 'Także twoja praca.' },
    panels: [
      { image: images.callcenter, label: 'Infolinia', caption: 'Odpowiada czatbot', alt: 'Konsultantka ze słuchawkami sama w nocnym call center, dookoła puste stanowiska.' },
      { image: images.legal, label: 'Asystent prawny', caption: 'Umowy czyta model', alt: 'Asystentka prawna nad stosem umów; obok laptop i gotowy stos przejrzanych dokumentów.' },
      { image: images.design, label: 'Grafik i copywriter', caption: 'Obrazy i teksty w sekundę', alt: 'Grafik patrzy na ścianę dziesiątek wygenerowanych projektów.' },
      { image: images.translator, label: 'Tłumacz', caption: 'Tłumaczenie od ręki', alt: 'Tłumaczka przy słownikach patrzy na strumień znaków z wielu alfabetów płynący w powietrzu.' },
      { image: images.warehouse, label: 'Magazyn', caption: 'Roboty już jeżdżą po halach', alt: 'Ogromny magazyn pełen autonomicznych robotów; jeden pracownik patrzy z antresoli.', focus: 'center 60%' },
      { image: images.driver, label: 'Kierowca', caption: 'Ciężarówki uczą się jeździć same', alt: 'Kierowca opiera się o swoją ciężarówkę i patrzy na przejeżdżającą ciężarówkę bez kierowcy.' },
    ],
    explain: [
      { image: images.legal, alt: 'Asystentka prawna nad stosem umów.', label: 'Zadania', title: 'Najpierw zadania, nie etaty.', copy: 'AI przejmuje maile, streszczenia i odpowiedzi. Etat jeszcze jest — ale coraz bardziej pusty w środku.' },
      { image: images.callcenter, alt: 'Puste stanowiska w call center.', label: 'Mniej rekrutacji', title: 'Jeden robi za pięciu.', copy: 'Firmy rzadko zwalniają od razu. Po prostu przestają zatrudniać. Najpierw tracą młodzi, którzy szukają pierwszej pracy.' },
      { image: images.warehouse, alt: 'Magazyn pełen robotów.', label: 'Hala i droga', title: 'Potem zmiana wychodzi z biura.', copy: 'Roboty w magazynach, ciężarówki bez kierowców. Najpierw praca przy komputerze, potem praca rękami.' },
    ],
    band: [
      {
        kind: 'stats',
        items: [
          { value: '1 na 4', label: 'miejsca pracy na świecie jest w zawodach narażonych na generatywną AI', source: sources.ilo },
          { value: '60%', label: 'miejsc pracy w bogatych krajach jest narażonych na AI', source: sources.imf },
          { value: '−11%', label: 'mniej zatrudnionych 22–25-latków w zawodach najbardziej narażonych na AI (2022–2026)', source: sources.stanford },
        ],
      },
      {
        kind: 'evidence',
        title: 'To już się dzieje',
        items: [
          { kicker: 'Salesforce · 2025', value: '9 000 → 5 000', text: 'osób w obsłudze klienta. „Potrzebuję mniej głów” — szef firmy.', source: sources.salesforce },
          { kicker: 'Klarna · 2025', value: '5 000 → 3 000', text: 'pracowników. Firma przestała zatrudniać, część pracy przejęła AI.', source: sources.klarna },
          { kicker: 'Amazon · 2025', text: 'Szef Amazona zapowiada, że AI zmniejszy liczbę pracowników biurowych firmy w najbliższych latach.', source: sources.amazon },
        ],
      },
      { kind: 'quote', quote: 'Przy rutynowej pracy umysłowej AI po prostu zastąpi wszystkich.', person: 'Geoffrey Hinton', role: 'noblista, „ojciec chrzestny AI”', source: sources.hintonDoac },
    ],
  },
  {
    id: 'hydraulik',
    number: '04',
    label: 'TO SIĘ PRZEBRANŻOWIĘ',
    status: 'MOŻLIWY SCENARIUSZ',
    chain: 'dochod',
    layout: 'triptych',
    title: { lead: 'Zostań hydraulikiem.', accent: 'Wszyscy naraz?' },
    panels: [
      { image: images.queue, label: 'Wszyscy do jednych drzwi', alt: 'Długa kolejka pracowników biurowych w deszczu przed szkołą zawodową.', focus: 'center 70%' },
      { image: images.tooMany, label: 'Za dużo fachowców', alt: 'Pięciu hydraulików z vanami czeka przed jednym domem.', focus: 'center 70%' },
      { image: images.robot, label: 'Robot już tu jest', alt: 'Humanoidalny robot na linii montażowej; stanowisko człowieka obok jest puste.', focus: 'center 65%' },
    ],
    explain: [
      { image: images.queue, alt: 'Kolejka do szkoły zawodowej.', label: 'Mało miejsc', title: 'Miejsc przy pracy fizycznej jest dużo mniej.', copy: 'Biura zatrudniają miliony ludzi. Fachowców potrzeba setki tysięcy. Nie zmieścimy się wszyscy.' },
      { image: images.tooMany, alt: 'Wielu hydraulików przed jednym domem.', label: 'Niższe stawki', title: 'Więcej chętnych — niższe stawki.', copy: 'Gdy pięciu fachowców walczy o jedno zlecenie, wygrywa najtańszy. A klient bez pensji nie remontuje łazienki.' },
      { image: images.robot, alt: 'Robot przy linii montażowej.', label: 'Roboty', title: 'A roboty też się uczą.', copy: 'AI przyspiesza budowę robotów. Praca fizyczna daje trochę czasu — ale może niewiele.' },
    ],
    band: [
      { kind: 'quote', quote: 'Minie dużo czasu, zanim AI będzie tak sprawna fizycznie jak my… dobrym zakładem byłoby zostać hydraulikiem.', person: 'Geoffrey Hinton', role: 'noblista, „ojciec chrzestny AI”', source: sources.hintonDoac },
      {
        kind: 'bars',
        title: 'Ilu chętnych na jedno miejsce?',
        subtitle: 'Przykład USA: ile osób pracuje w zawodzie',
        bars: [
          { label: 'Konsultanci obsługi klienta', value: 2900000, display: '2,9 mln' },
          { label: 'Hydraulicy', value: 510600, display: '511 tys.' },
          { label: 'Wolne miejsca dla hydraulików rocznie', value: 42000, display: '42 tys.', highlight: true },
        ],
        caption: 'Na jedno wolne miejsce hydraulika przypada prawie 70 osób — z samej obsługi klienta.',
        source: sources.bls,
      },
      {
        kind: 'stats',
        items: [
          { value: '11 h', label: 'tyle AI potrzebowała, by stworzyć równowartość 9 miesięcy ludzkich pokazów do nauki robotów', source: sources.nvidia },
          { value: '−40%', label: 'tyle spadł koszt budowy humanoidalnego robota — analitycy zakładali 15–20% rocznie', source: sources.goldman },
        ],
      },
      { kind: 'quote', quote: 'Potężna AI będzie w stanie przyspieszyć rozwój robotów, a potem nimi sterować. To może dać trochę czasu… ale obawiam się, że niewiele.', person: 'Dario Amodei', role: 'CEO, Anthropic', source: sources.amodei },
    ],
  },
  {
    id: 'popyt',
    number: '05',
    label: 'CO DZIEJE SIĘ DALEJ',
    status: 'MOŻLIWY SCENARIUSZ',
    chain: 'zakupy',
    layout: 'triptych',
    title: { lead: 'Nie masz pensji.', accent: 'Nie kupujesz.' },
    panels: [
      { image: images.bills, label: 'Dom tnie wydatki', alt: 'Para przy kuchennym stole nad rachunkami; nowy telefon w pudełku do zwrotu.', focus: 'center 70%' },
      { image: images.emptyStore, label: 'Sklep bez klientów', alt: 'Salon z telefonami w galerii handlowej, bez ani jednego klienta.', focus: 'center 70%' },
      { image: images.closing, label: 'Firma zamyka drzwi', alt: 'Właściciel kawiarni stawia krzesła na stołach w ostatni wieczór przed zamknięciem.', focus: 'center 65%' },
    ],
    explain: [
      { image: images.bills, alt: 'Para liczy rachunki.', label: 'Pensja', title: 'Twoja pensja to czyjś utarg.', copy: 'Kiedy nie zarabiasz, nie kupujesz telefonu, auta ani obiadu na mieście. Gospodarka to krąg.' },
      { image: images.emptyStore, alt: 'Pusty sklep z elektroniką.', label: 'Maszyny nie kupują', title: 'Maszyna produkuje, ale nie kupuje.', copy: 'AI może zrobić więcej towarów i usług niż kiedykolwiek. Ale robot nie wyda pensji w sklepie.' },
      { image: images.closing, alt: 'Zamykana kawiarnia.', label: 'Spirala', title: 'Mniej zakupów — kolejne zwolnienia.', copy: 'Sklepy i firmy zarabiają mniej, więc tną koszty. Najtańsza jest AI. Pętla się zamyka.' },
    ],
    band: [
      { kind: 'loop', title: 'Pętla bez hamulca', steps: ['Mniej pensji', 'Mniej zakupów', 'Firmy zarabiają mniej', 'Kolejne zwolnienia', 'AI jeszcze tańsza'], caption: 'To scenariusz, nie prognoza. Ale każdy krok wynika z poprzedniego.' },
      { kind: 'quote', quote: 'A jak ty zmusisz te roboty, żeby kupowały Fordy?', person: 'Walter Reuther', role: 'przywódca związku robotników motoryzacji, do dyrektora Forda — anegdota z lat 50.', source: sources.reuther },
      {
        kind: 'evidence',
        title: 'Co mówią eksperci',
        items: [
          { kicker: 'Citrini Research · 2026 · scenariusz', value: 'Zero', text: '„Ile maszyny wydają na zakupy? Zero.” Autorzy opisują pętlę „bez naturalnego hamulca”.', source: sources.citrini },
          { kicker: 'Geoffrey Hinton · 2025', text: '„Kilka osób stanie się dużo bogatszych, a większość biedniejsza.”', source: sources.hintonFt },
          { kicker: 'Citadel Securities · 2026 · kontra', text: 'Wcześniejsze fale technologii nie sprawiły, że praca ludzi stała się zbędna.', source: sources.citadel },
        ],
      },
    ],
  },

  {
    id: 'panstwo',
    number: '06',
    label: 'CO Z TEGO MA PAŃSTWO',
    status: 'DZIŚ',
    chain: 'podatki',
    layout: 'triptych',
    title: { lead: 'Państwo żyje z twojej pracy.', accent: 'Co, jeśli jej nie będzie?' },
    panels: [
      { image: images.workFunds, label: 'Praca płaci za wspólne', alt: 'Ludzie idą rano do pracy; w tle szkoła, szpital z karetką i autobus miejski.', focus: 'center 70%' },
      { image: images.cuts, label: 'Budżet się kurczy', alt: 'Zmęczeni urzędnicy nad budżetem skreślają całe pozycje czerwonym długopisem.', focus: 'center 65%' },
      { image: images.strain, label: 'Usługi pękają', alt: 'Zatłoczona izba przyjęć w nocy; ludzie czekają na korytarzu, pielęgniarka biegnie.', focus: 'center 65%' },
    ],
    explain: [
      { image: images.workFunds, alt: 'Ludzie idą do pracy obok szkoły i szpitala.', label: 'Nasze pieniądze', title: 'Państwo nie ma własnych pieniędzy.', copy: 'Ma nasze. Szkoły, szpitale, drogi i emerytury opłacamy głównie z podatków od pracy i zakupów.' },
      { image: images.cuts, alt: 'Urzędnicy tną budżet.', label: 'Nożyce', title: 'Mniej wpływów, więcej potrzeb.', copy: 'Bezrobotny nie płaci podatku od pensji — za to potrzebuje wsparcia. Pieniędzy ubywa dokładnie wtedy, gdy trzeba ich więcej.' },
      { image: images.strain, alt: 'Przepełniona izba przyjęć.', label: 'Cięcia', title: 'Cięcia trafiają w to, co wspólne.', copy: 'Gdy dotyczy to milionów ludzi naraz, państwo tnie: mniej lekarzy, nauczycieli i kursów autobusów.' },
    ],
    band: [
      {
        kind: 'taxSplit',
        title: 'Skąd państwo ma pieniądze?',
        subtitle: 'Z każdych 100 zapłaconych podatków — średnia bogatych krajów (OECD), 2023',
        parts: [
          { label: 'z pracy', detail: 'podatek od pensji i składki', value: 50, highlight: true },
          { label: 'z zakupów', detail: 'VAT i inne', value: 31, highlight: true },
          { label: 'z zysków firm', value: 12 },
          { label: 'inne', value: 7 },
        ],
        caption: '8 na 10 pieniędzy państwa bierze się z tego, że ludzie zarabiają i wydają.',
        countriesLabel: 'Z pracy (na 100):',
        countries: [{ name: 'USA', value: 64 }, { name: 'Niemcy', value: 65 }, { name: 'Japonia', value: 57 }, { name: 'Francja', value: 55 }, { name: 'Wielka Brytania', value: 49 }],
        source: sources.oecd,
      },
      { kind: 'scissors', title: 'Nożyce', income: 'wpływy z podatków', spending: 'wydatki na wsparcie', caption: 'Schemat, nie dane. Przy masowym bezrobociu wpływy spadają, a wydatki rosną — w tym samym momencie.' },
      { kind: 'quote', quote: 'Recesja na rynku pracy spowoduje tąpnięcie we wpływach podatkowych, osłabiając usługi publiczne i zagrażając programom opieki społecznej wtedy, gdy będą najbardziej potrzebne.', person: 'Mustafa Suleyman', role: '„Nadchodząca fala”, rozdz. 10', source: sources.book },
      { kind: 'quote', quote: 'Baza dochodów państwa to w istocie podatek od ludzkiego czasu.', person: 'Citrini Research', role: 'scenariusz „The 2028 Global Intelligence Crisis”, 2026', source: sources.citrini },
    ],
  },
  {
    id: 'historia',
    number: '07',
    label: 'CZY LUDZIE SIĘ ZBUNTUJĄ',
    status: 'HISTORIA',
    chain: 'zaufanie',
    layout: 'triptych',
    title: { lead: 'To już było.', accent: 'Wtedy nie było AI.' },
    panels: [
      { image: images.depression, label: 'Wielki Kryzys', alt: 'Lata 30.: długa kolejka bezrobotnych mężczyzn przed jadłodajnią zimą.', focus: 'center 65%' },
      { image: images.factory, label: 'Upadek przemysłu', alt: 'Opuszczona fabryka, zardzewiała brama na łańcuch; przed nią stoi dawny pracownik.', focus: 'center 70%' },
      { image: images.anger, label: 'Gniew', alt: 'Nocny protest: tłum z uniesionymi pięściami, race, w oddali kordon policji.', focus: 'center 70%' },
    ],
    explain: [
      { image: images.depression, alt: 'Kolejka bezrobotnych.', label: 'Godność', title: 'Praca to nie tylko pieniądze.', copy: 'To godność i miejsce w świecie. Hinton: „dla wielu ludzi ich godność jest związana z pracą”.' },
      { image: images.factory, alt: 'Zamknięta fabryka.', label: 'Polityka', title: 'Prywatny dramat staje się polityką.', copy: 'Gdy bez pracy zostają miliony naraz, rośnie gniew i szukanie winnych. Skutki trwają pokolenia.' },
      { image: images.anger, alt: 'Protest w nocy.', label: 'Tempo', title: 'Wtedy zmiany trwały lata.', copy: 'AI zmienia się co kilka miesięcy. Państwa i ludzie mogą nie zdążyć.' },
    ],
    band: [
      {
        kind: 'stats',
        items: [
          { value: '24,9%', label: 'bezrobocia w USA w 1933 r. — 12,8 mln ludzi bez pracy', source: sources.fdr },
          { value: '6 mln', label: 'bezrobotnych w Niemczech w 1932 r. — mniej więcej co czwarty pracownik', source: sources.germany },
          { value: '<20%', label: 'Amerykanów ufa dziś rządowi. Kiedyś ponad 70%', source: sources.book },
        ],
      },
      {
        kind: 'evidence',
        title: 'Co przyszło potem',
        items: [
          { kicker: 'Niemcy · 1930–1932', value: '18% → 37%', text: 'poparcia dla NSDAP. Badania: regiony mocniej dotknięte cięciami częściej głosowały na nazistów.', source: sources.nsdap },
          { kicker: 'USA · po upadku przemysłu', text: '„Śmierci z rozpaczy” — narkotyki, alkohol, samobójstwa wśród ludzi, którzy stracili stabilną pracę.', source: sources.deaton },
          { kicker: 'Wielka Brytania · dekady po kopalniach', value: '42%', text: 'mieszkańców dawnych zagłębi węglowych wciąż żyje w najbiedniejszych obszarach kraju.', source: sources.coalfields },
        ],
      },
      { kind: 'quote', quote: 'Fundamentem demokracji jest zaufanie.', person: 'Mustafa Suleyman', role: '„Nadchodząca fala”, rozdz. 9', source: sources.book },
    ],
  },
];
