import type { SceneStatus } from '@features/upcomingWave/types/scene.types';

import { paths } from '@routes/paths';

export const ui = {
  lang: 'pl',
  brand: 'Upcoming Wave',
  langSwitch: { label: 'EN', href: paths.en, ariaLabel: 'English version' } as null | { label: string; href: string; ariaLabel: string },
  dominoAria: 'Łańcuch skutków',
  status: {
    today: 'DZIŚ',
    history: 'HISTORIA',
    incident: 'INCYDENT',
    possible: 'MOŻLIWY SCENARIUSZ',
    possibleMany: 'MOŻLIWE SCENARIUSZE',
    extreme: 'SKRAJNY SCENARIUSZ',
    answer: 'ODPOWIEDŹ',
  } satisfies Record<SceneStatus, string>,
  quoteMarks: { open: '„', close: '”' },
  why: 'Dlaczego?',
  copyLink: 'Kopiuj link do tej sekcji',
  facts: { show: (count: number) => `Pokaż fakty i źródła (${count})`, hide: 'Zwiń fakty i źródła', moreVoices: (count: number) => `+${count} kolejne głosy`, lessVoices: 'Zwiń głosy', allSteps: (count: number) => `Pokaż wszystkie kroki (${count})`, fewerSteps: 'Pokaż mniej' },
  readingMode: { toShort: 'Skrót', toFull: 'Pełna wersja', aria: 'Przełącz między skrótem a pełną wersją' },
  stories: { open: 'Obejrzyj w 30 sekund', aria: 'Cała strona w 30 sekund', close: 'Zamknij' },
  stepsAria: 'Co się dzieje, krok po kroku',
  factsAria: 'Fakty i źródła',
  explain: {
    eyebrow: 'Dlaczego?',
    close: 'Zamknij wyjaśnienie',
    prev: 'Poprzedni krok',
    next: 'Następny krok',
    done: 'Rozumiem',
    chainAria: 'Łańcuch przyczyn',
    slide: 'slajd',
    step: 'Krok',
    stepOf: (index: number, total: number) => `Krok ${index} z ${total}`,
  },
  voices: {
    eyebrow: 'Głosy · to nie są aktywiści',
    titleLead: 'To nie my to mówimy.',
    titleAccent: 'Mówią to oni.',
    text: 'Szefowie firm, które budują AI, i naukowcy, którzy ją wymyślili. Każdy cytat ma link do źródła.',
    signedBy: 'Podpisali m.in.',
    source: 'Źródło:',
  },
  pond: {
    replay: 'Jeszcze raz ↻',
    day: 'Dzień',
    nothing: 'prawie nic',
    percentOfPond: (percent: number) => `${percent}% stawu`,
    aria: (day: number, percent: string) => `Dzień ${day}: lilie pokrywają ${percent}% stawu`,
    lessThanOne: 'mniej niż 1',
  },
  chart: {
    decimal: ',',
    day: '1 dzień pracy',
    week: '1 tydzień pracy',
    ifContinues: 'jeśli tak dalej ↑',
    uncertain: 'pomiar niepewny',
    showAll: 'Pokaż wszystkie pomiary',
    columns: ['Model', 'Data', 'Zadania do'],
    aria: (title: string, last: string, subtitle: string) => `${title}: od 4 minut w 2023 r. do około ${last} w 2026 r. ${subtitle}`,
  },
  consent: { text: 'Używamy Google Analytics, żeby wiedzieć, które sekcje ludzie czytają. Bez reklam i bez sprzedawania danych.', accept: 'Zgoda', decline: 'Nie, dziękuję' },
  scissorsShock: 'fala zwolnień',
};
