import type { SceneStatus } from '@features/upcomingWave/types/scene.types';

export const ui = {
  lang: 'pl',
  brand: 'Nadchodząca fala',
  languagePicker: 'Wybierz język',
  dominoAria: 'Łańcuch skutków',
  status: {
    today: 'DZIŚ',
    history: 'HISTORIA',
    incident: 'INCYDENT',
    possible: 'MOŻLIWY SCENARIUSZ',
    possibleMany: 'MOŻLIWE SCENARIUSZE',
    extreme: 'SKRAJNY SCENARIUSZ',
    answer: 'DROGA NAPRZÓD',
  } satisfies Record<SceneStatus, string>,
  quoteMarks: { open: '„', close: '”' },
  why: 'Dlaczego?',
  copyLink: 'Kopiuj link do tej sekcji',
  facts: { moreVoices: (count: number) => `+${count} ${count === 1 ? 'kolejny głos' : count % 10 >= 2 && count % 10 <= 4 && (count % 100 < 12 || count % 100 > 14) ? 'kolejne głosy' : 'kolejnych głosów'}`, lessVoices: 'Zwiń głosy' },
  upside: { label: 'Jeśli zrobimy to dobrze' },
  readMore: 'Czytaj więcej',
  showLess: 'Zwiń sekcję',
  chapterEnd: 'Koniec rozdziału',
  stepsAria: 'Co się dzieje, krok po kroku',
  factsAria: 'Fakty i źródła',
  explain: {
    eyebrow: 'Dlaczego?',
    close: 'Zamknij wyjaśnienie',
    prev: 'Poprzedni krok',
    next: 'Następny krok',
    done: 'Rozumiem',
    chainAria: 'Łańcuch przyczyn',
    slide: 'slajd',
    step: 'Krok',
    stepOf: (index: number, total: number) => `Krok ${index} z ${total}`,
  },
  voices: {
    eyebrow: 'Głosy · z wnętrza branży',
    titleLead: 'Zgadzają się w dwóch sprawach.',
    titleAccent: 'To może być przełom. I potrzebne są zasady.',
    text: 'Szefowie firm, które budują AI, i naukowcy, którzy byli jej pionierami. Każdy cytat ma link do źródła.',
    signedBy: 'Podpisali m.in.',
    source: 'Źródło:',
    swipe: 'Przesuń, by zobaczyć więcej →',
  },
  pond: {
    replay: 'Jeszcze raz ↻',
    day: 'Dzień',
    nothing: 'prawie nic',
    percentOfPond: (percent: number) => `${percent}% stawu`,
    aria: (day: number, percent: string) => `Dzień ${day}: lilie pokrywają ${percent}% stawu`,
    lessThanOne: 'mniej niż 1',
  },
  chart: {
    decimal: ',',
    day: '1 dzień pracy',
    week: '1 tydzień pracy',
    ifContinues: 'jeśli tak pójdzie dalej ↑',
    uncertain: 'pomiar niepewny',
    showAll: 'Pokaż wszystkie pomiary',
    columns: ['Model', 'Data', 'Zadania do'],
    aria: (title: string, last: string, subtitle: string) => `${title}: od 4 minut w 2023 r. do około ${last} w 2026 r. ${subtitle}`,
  },
  consent: { text: 'Używam Google Analytics, żeby wiedzieć, które sekcje ludzie czytają. Bez reklam i bez sprzedawania danych.', accept: 'Akceptuję', decline: 'Nie, dziękuję' },
  scissorsShock: 'fala zwolnień',
  scissorsAria: (income: string, spending: string, caption: string) => `${income} spadają, ${spending} rosną. ${caption}`,
};
