import type { SceneStatus } from '../../types/scene.types';

export const ui = {
  lang: 'pl',
  brand: 'Nadchodząca fala',
  langSwitch: { label: 'EN', href: '/', ariaLabel: 'English version' } as null | { label: string; href: string; ariaLabel: string },
  dominoAria: 'Łańcuch skutków',
  heroBasis: 'Na podstawie „Nadchodzącej fali” i słów twórców AI',
  status: {
    today: 'DZIŚ',
    history: 'HISTORIA',
    incident: 'INCYDENT',
    possible: 'MOŻLIWY SCENARIUSZ',
    possibleMany: 'MOŻLIWE SCENARIUSZE',
    extreme: 'SKRAJNY SCENARIUSZ',
    answer: 'ODPOWIEDŹ',
  } satisfies Record<SceneStatus, string>,
  why: 'Dlaczego?',
  copyLink: 'Kopiuj link do tej sekcji',
  stepsAria: 'Co się dzieje, krok po kroku',
  factsAria: 'Fakty i źródła',
  explain: {
    eyebrow: 'Dlaczego?',
    close: 'Zamknij wyjaśnienie',
    prev: 'Poprzedni krok',
    next: 'Następny krok',
    done: 'Rozumiem',
    chainAria: 'Łańcuch przyczyn',
    slide: 'slajd',
    step: 'Krok',
    stepOf: (index: number, total: number) => `Krok ${index} z ${total}`,
  },
  voices: {
    eyebrow: 'Głosy · to nie są aktywiści',
    titleLead: 'To nie my to mówimy.',
    titleAccent: 'Mówią to oni.',
    text: 'Szefowie firm, które budują AI, i naukowcy, którzy ją wymyślili. Każdy cytat ma link do źródła.',
    signedBy: 'Podpisali m.in.',
    source: 'Źródło:',
  },
  pond: {
    replay: 'Jeszcze raz ↻',
    day: 'Dzień',
    nothing: 'prawie nic',
    percentOfPond: (percent: number) => `${percent}% stawu`,
    aria: (day: number, percent: string) => `Dzień ${day}: lilie pokrywają ${percent}% stawu`,
    lessThanOne: 'mniej niż 1',
  },
  chart: {
    decimal: ',',
    day: '1 dzień pracy',
    week: '1 tydzień pracy',
    ifContinues: 'jeśli tak dalej ↑',
    uncertain: 'pomiar niepewny',
    showAll: 'Pokaż wszystkie pomiary',
    columns: ['Model', 'Data', 'Zadania do'],
    aria: (title: string, last: string, subtitle: string) => `${title}: od 4 minut w 2023 r. do około ${last} w 2026 r. ${subtitle}`,
  },
  scissorsShock: 'fala zwolnień',
};
