import type { Voice } from '@features/upcomingWave/types/voice.types';

// Every quote is verified against the linked source; Polish text is our translation
// unless it comes from the Polish edition of the book.
export const voices: Voice[] = [
  {
    id: 'cais',
    featured: true,
    variant: 'statement',
    image: '/images/v2/voice-cais-v1.jpg',
    imageAlt: 'Sala kryzysowa: trzy ekrany obok siebie — wirus, grzyb atomowy i sieć neuronowa.',
    quotes: ['Ograniczanie ryzyka wyginięcia ludzkości z powodu AI powinno być globalnym priorytetem — obok pandemii i wojny nuklearnej.'],
    originals: ['Mitigating the risk of extinction from AI should be a global priority alongside other societal-scale risks such as pandemics and nuclear war.'],
    person: 'Wspólne oświadczenie o ryzyku AI',
    role: 'Center for AI Safety',
    context: 'Maj 2023',
    source: { label: 'safe.ai', url: 'https://safe.ai/work/statement-on-ai-risk' },
    signatories: ['Sam Altman · OpenAI', 'Demis Hassabis · Google DeepMind', 'Dario Amodei · Anthropic', 'Geoffrey Hinton · noblista', 'Yoshua Bengio · Mila', 'Bill Gates'],
  },
  {
    id: 'hinton',
    featured: true,
    variant: 'figure',
    image: '/images/v2/voice-hinton-v1.jpg',
    imageAlt: 'Mały człowiek stoi przed ogromną, świetlistą strukturą inteligencji.',
    figure: '10\u2009–\u200920%',
    figureCaption: 'szans, że AI doprowadzi do wyginięcia ludzkości w ciągu 30 lat — tak ocenia to ryzyko.',
    quotes: ['Nigdy wcześniej nie mieliśmy do czynienia z czymś inteligentniejszym od nas.'],
    originals: ['We’ve never had to deal with things more intelligent than ourselves before.'],
    person: 'Geoffrey Hinton',
    role: 'Noblista, „ojciec chrzestny AI”',
    context: 'BBC Radio 4 · grudzień 2024',
    source: { label: 'Irish Examiner / Guardian', url: 'https://www.irishexaminer.com/world/arid-41544136.html' },
  },
  {
    id: 'hassabis',
    featured: true,
    variant: 'figure',
    image: '/images/v2/benefit-02-science-v1.jpg',
    imageAlt: 'Naukowczyni patrzy na świetlisty trójwymiarowy model białka.',
    figure: '~10 lat',
    figureCaption: 'tyle, jego zdaniem, może dzielić nas od wyleczenia wszystkich chorób — „nie widzę, czemu nie”.',
    quotes: ['Pewnego dnia może uda nam się wyleczyć wszystkie choroby z pomocą AI.'],
    person: 'Demis Hassabis',
    role: 'CEO, Google DeepMind · noblista',
    context: 'CBS 60 Minutes · 2025',
    source: { label: 'CBS News', url: 'https://www.cbsnews.com/news/artificial-intelligence-google-deepmind-ceo-demis-hassabis-60-minutes-transcript/' },
  },
  {
    id: 'gates',
    featured: true,
    variant: 'plain',
    image: '/images/v2/benefit-03-time-v1.jpg',
    imageAlt: 'Nauczycielka klęczy przy dziecku i pomaga mu w lekcjach.',
    quotes: ['Rozwój AI jest tak fundamentalny jak stworzenie mikroprocesora, komputera osobistego, internetu i telefonu komórkowego.', 'AI może zmniejszyć niektóre z największych nierówności na świecie.'],
    person: 'Bill Gates',
    role: 'współzałożyciel Microsoftu · Fundacja Gatesów',
    context: 'GatesNotes · marzec 2023',
    source: { label: 'GatesNotes', url: 'https://www.gatesnotes.com/The-Age-of-AI-Has-Begun' },
  },
  {
    id: 'altman',
    featured: true,
    variant: 'statement',
    image: '/images/v2/voice-altman-v1.jpg',
    imageAlt: 'Pusta sala przesłuchań Senatu USA: stolik świadka z mikrofonem naprzeciw ławy senatorów.',
    quotes: [
      'Jeśli ta technologia pójdzie w złą stronę, może pójść bardzo źle.',
      'Uważamy, że interwencja regulacyjna rządów będzie kluczowa, by ograniczać ryzyko coraz potężniejszych modeli.',
    ],
    originals: [
      'If this technology goes wrong, it can go quite wrong.',
      'We think that regulatory intervention by governments will be critical to mitigate the risks of increasingly powerful models.',
    ],
    person: 'Sam Altman',
    role: 'CEO, OpenAI — twórca ChatGPT',
    context: 'Zeznanie przed Senatem USA · 16 maja 2023',
    source: { label: 'Al Jazeera', url: 'https://www.aljazeera.com/news/2023/5/17/chatgpt-boss-tells-us-legislators-regulation-critical-for-ai' },
  },
  {
    id: 'amodei',
    variant: 'figure',
    image: '/images/v2/voice-amodei-v1.jpg',
    imageAlt: 'Puste biuro o świcie, na biurkach kartony z rzeczami zwolnionych pracowników.',
    figure: '50%',
    figureCaption: 'początkowych stanowisk biurowych może zniknąć w ciągu 5 lat, a bezrobocie skoczyć do 10–20% — mówił w 2025 r. W 2026 r. złagodził tę prognozę.',
    quotes: ['Jako twórcy tej technologii mamy obowiązek uczciwie mówić o tym, co nadchodzi.'],
    originals: ['We, as the producers of this technology, have a duty and an obligation to be honest about what is coming.'],
    person: 'Dario Amodei',
    role: 'CEO, Anthropic',
    context: 'Axios · maj 2025',
    source: { label: 'Axios', url: 'https://www.axios.com/2025/05/28/ai-jobs-white-collar-unemployment-anthropic' },
  },
  {
    id: 'fli',
    variant: 'figure',
    image: '/images/v2/voice-fli-v1.jpg',
    imageAlt: 'Ściana pokryta tysiącami podpisów; ręka dodaje kolejny.',
    figure: '31 000+',
    figureCaption: 'podpisów pod apelem o co najmniej 6 miesięcy przerwy w trenowaniu najpotężniejszych systemów. Wśród nich Elon Musk i Steve Wozniak.',
    quotes: ['Czy powinniśmy ryzykować utratę kontroli nad naszą cywilizacją?'],
    originals: ['Should we risk loss of control of our civilization?'],
    person: 'List otwarty „Pause Giant AI Experiments”',
    role: 'Future of Life Institute',
    context: 'Marzec 2023',
    source: { label: 'futureoflife.org', url: 'https://futureoflife.org/open-letter/pause-giant-ai-experiments/' },
  },
  {
    id: 'suleyman',
    variant: 'plain',
    image: '/images/v2/voice-suleyman-v1.jpg',
    imageAlt: 'Otwarta książka w laboratorium; z jej stron unosi się helisa DNA zmieniająca się w wirusa.',
    quotes: ['Jeden eksperyment z patogenami, niewinne dłubanie w materii na poziomie cząsteczkowym, może wywołać pandemię o globalnych konsekwencjach.'],
    person: 'Mustafa Suleyman',
    role: 'Współzałożyciel DeepMind, autor książki',
    context: '„Nadchodząca fala”, rozdz. 7 · 2023',
    source: { label: 'polskie wydanie książki' },
  },
];
