import type { SceneStatus } from '@features/upcomingWave/types/scene.types';

export const ui = {
  lang: 'fr',
  brand: 'Upcoming Wave',
  languagePicker: 'Choisir la langue',
  dominoAria: 'Chaîne de conséquences',
  status: {
    today: 'AUJOURD’HUI',
    history: 'HISTOIRE',
    incident: 'INCIDENT',
    possible: 'SCÉNARIO POSSIBLE',
    possibleMany: 'SCÉNARIOS POSSIBLES',
    extreme: 'SCÉNARIO EXTRÊME',
    answer: 'UNE VOIE À SUIVRE',
  } satisfies Record<SceneStatus, string>,
  quoteMarks: { open: '« ', close: ' »' },
  why: 'Pourquoi ?',
  copyLink: 'Copier le lien vers cette section',
  facts: { moreVoices: (count: number) => `+${count} autres voix`, lessVoices: 'Afficher moins de voix' },
  upside: { label: 'Si nous faisons les bons choix' },
  readMore: 'Lire la suite',
  showLess: 'Réduire',
  chapterEnd: 'Fin du chapitre',
  readingMode: { toShort: 'Version courte', toFull: 'Version complète', aria: 'Basculer entre la version courte et la version complète' },
  stepsAria: 'Ce qui se passe, étape par étape',
  factsAria: 'Faits et sources',
  explain: {
    eyebrow: 'Pourquoi ?',
    close: 'Fermer l’explication',
    prev: 'Étape précédente',
    next: 'Étape suivante',
    done: 'Compris',
    chainAria: 'Chaîne de causes',
    slide: 'diapositive',
    step: 'Étape',
    stepOf: (index: number, total: number) => `Étape ${index} sur ${total}`,
  },
  voices: {
    eyebrow: 'Voix · de l’intérieur du secteur',
    titleLead: 'Ils s’accordent sur deux points.',
    titleAccent: 'L’enjeu peut être immense. Il faut des règles.',
    text: 'Les dirigeants des entreprises qui construisent l’IA et les scientifiques qui en ont été les pionniers. Chaque citation renvoie à sa source.',
    signedBy: 'Signataires, entre autres',
    source: 'Source :',
    swipe: 'Glissez pour voir plus →',
  },
  pond: {
    replay: 'Rejouer ↻',
    day: 'Jour',
    nothing: 'presque rien',
    percentOfPond: (percent: number) => `${percent}\u00A0% de l’étang`,
    aria: (day: number, percent: string) => `Jour ${day}\u00A0: les nénuphars couvrent ${percent}\u00A0% de l’étang`,
    lessThanOne: 'moins de 1',
  },
  chart: {
    decimal: ',',
    day: '1 journée de travail',
    week: '1 semaine de travail',
    ifContinues: 'si ça continue ↑',
    uncertain: 'mesure incertaine',
    showAll: 'Afficher toutes les mesures',
    columns: ['Modèle', 'Date', 'Tâches jusqu’à'],
    aria: (title: string, last: string, subtitle: string) => `${title}\u00A0: de 4 minutes en 2023 à environ ${last} en 2026. ${subtitle}`,
  },
  consent: { text: 'J’utilise Google Analytics pour voir quelles sections sont lues. Pas de publicité, pas de revente de données.', accept: 'Accepter', decline: 'Non merci' },
  scissorsShock: 'vague de licenciements',
  scissorsAria: (income: string, spending: string, caption: string) => `Les ${income} baissent, les ${spending} augmentent. ${caption}`,
};
