import type { Voice } from '@features/upcomingWave/types/voice.types';

// French translations of the original English quotes (verified against the linked source).
// The Suleyman line is our translation of the English edition (ch. 7).
export const voices: Voice[] = [
  {
    id: 'cais',
    featured: true,
    variant: 'statement',
    image: '/images/v2/voice-cais-v1.jpg',
    imageAlt: 'Une cellule de crise : trois écrans côte à côte - un virus, un champignon atomique et un réseau de neurones.',
    quotes: ['Réduire le risque d’extinction lié à l’IA devrait être une priorité mondiale, au même titre que d’autres risques à l’échelle de la société, comme les pandémies et la guerre nucléaire.'],
    person: 'Déclaration sur le risque lié à l’IA',
    role: 'Center for AI Safety',
    context: 'Mai 2023',
    source: { label: 'safe.ai', url: 'https://safe.ai/work/statement-on-ai-risk' },
    signatories: ['Sam Altman · OpenAI', 'Demis Hassabis · Google DeepMind', 'Dario Amodei · Anthropic', 'Geoffrey Hinton · prix Nobel', 'Yoshua Bengio · Mila', 'Bill Gates'],
  },
  {
    id: 'hinton',
    featured: true,
    variant: 'figure',
    image: '/images/v2/voice-hinton-v1.jpg',
    imageAlt: 'Une petite silhouette face à une immense structure d’intelligence lumineuse.',
    figure: '10-20 %',
    figureCaption: 'de risque que l’humanité s’éteigne à cause de l’IA d’ici 30 ans, selon son estimation.',
    quotes: ['Nous n’avons jamais eu affaire à des choses plus intelligentes que nous.'],
    person: 'Geoffrey Hinton',
    role: 'Prix Nobel, le « parrain de l’IA »',
    context: 'BBC Radio 4 · décembre 2024',
    source: { label: 'Irish Examiner / Guardian', url: 'https://www.irishexaminer.com/world/arid-41544136.html' },
  },
  {
    id: 'hassabis',
    featured: true,
    variant: 'figure',
    image: '/images/v2/benefit-02-science-v1.jpg',
    imageAlt: 'Une scientifique observe un modèle 3D lumineux de protéine.',
    figure: 'Peut-être 10 ans',
    figureCaption: 'avant que l’IA puisse aider à guérir toutes les maladies, espère-t-il - « je ne vois pas pourquoi ce ne serait pas possible ».',
    quotes: ['Un jour, peut-être, nous pourrons guérir toutes les maladies avec l’aide de l’IA.'],
    person: 'Demis Hassabis',
    role: 'PDG de Google DeepMind · prix Nobel',
    context: 'CBS 60 Minutes · 2025',
    source: { label: 'CBS News', url: 'https://www.cbsnews.com/news/artificial-intelligence-google-deepmind-ceo-demis-hassabis-60-minutes-transcript/' },
  },
  {
    id: 'gates',
    featured: true,
    variant: 'plain',
    image: '/images/v2/benefit-03-time-v1.jpg',
    imageAlt: 'Une enseignante agenouillée aide un enfant à faire ses devoirs.',
    quotes: ['Le développement de l’IA est aussi fondamental que la création du microprocesseur, de l’ordinateur personnel, d’Internet et du téléphone mobile.', 'L’IA peut réduire certaines des pires inégalités du monde.'],
    person: 'Bill Gates',
    role: 'Cofondateur de Microsoft · Gates Foundation',
    context: 'GatesNotes · mars 2023',
    source: { label: 'GatesNotes', url: 'https://www.gatesnotes.com/The-Age-of-AI-Has-Begun' },
  },
  {
    id: 'altman',
    featured: true,
    variant: 'statement',
    image: '/images/v2/voice-altman-v1.jpg',
    imageAlt: 'Une salle d’audition vide du Sénat américain : une table de témoin avec un micro, face à l’estrade des sénateurs.',
    quotes: [
      'Si cette technologie tourne mal, elle peut tourner vraiment mal.',
      'Nous pensons que l’intervention réglementaire des gouvernements sera essentielle pour atténuer les risques de modèles de plus en plus puissants.',
    ],
    person: 'Sam Altman',
    role: 'PDG d’OpenAI, créateur de ChatGPT',
    context: 'Audition au Sénat américain · 16 mai 2023',
    source: { label: 'Al Jazeera', url: 'https://www.aljazeera.com/news/2023/5/17/chatgpt-boss-tells-us-legislators-regulation-critical-for-ai' },
  },
  {
    id: 'amodei',
    variant: 'figure',
    image: '/images/v2/voice-amodei-v1.jpg',
    imageAlt: 'Un bureau vide à l’aube, des cartons avec les affaires d’employés licenciés posés sur les tables.',
    figure: '50 %',
    figureCaption: 'des postes de bureau pour débutants pourraient disparaître d’ici 5 ans, avec un chômage grimpant à 10-20 %, avertissait-il en 2025. En 2026, il a nuancé cette prévision.',
    quotes: ['Nous, qui produisons cette technologie, avons le devoir et l’obligation d’être honnêtes sur ce qui arrive.'],
    person: 'Dario Amodei',
    role: 'PDG d’Anthropic',
    context: 'Axios · mai 2025',
    source: { label: 'Axios', url: 'https://www.axios.com/2025/05/28/ai-jobs-white-collar-unemployment-anthropic' },
  },
  {
    id: 'fli',
    variant: 'figure',
    image: '/images/v2/voice-fli-v1.jpg',
    imageAlt: 'Un mur couvert de milliers de signatures ; une main en ajoute une.',
    figure: 'Plus de 31 000',
    figureCaption: 'signatures pour un appel à une pause d’au moins 6 mois dans l’entraînement des systèmes les plus puissants. Parmi les signataires : Elon Musk et Steve Wozniak.',
    quotes: ['Devons-nous risquer de perdre le contrôle de notre civilisation ?'],
    person: 'Lettre ouverte « Pause Giant AI Experiments »',
    role: 'Future of Life Institute',
    context: 'Mars 2023',
    source: { label: 'futureoflife.org', url: 'https://futureoflife.org/open-letter/pause-giant-ai-experiments/' },
  },
  {
    id: 'suleyman',
    variant: 'plain',
    image: '/images/v2/voice-suleyman-v1.jpg',
    imageAlt: 'Un livre ouvert dans un laboratoire ; une hélice d’ADN s’élève de ses pages et se transforme en virus.',
    quotes: ['Une seule expérience pathogène pourrait déclencher une pandémie, un minuscule événement moléculaire aux répercussions mondiales.'],
    person: 'Mustafa Suleyman',
    role: 'PDG de Microsoft AI, cofondateur de DeepMind, coauteur du livre',
    context: '« The Coming Wave », chap. 7 · 2023',
    source: { label: 'le livre' },
  },
];
